"""
Auto-generated accounts resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class AccountsResource:
    """
    Manage connected social media accounts.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.

        Enum members are unwrapped to their value: httpx serializes params
        via str(), which yields "ClassName.MEMBER" for Enum members, so
        e.g. ``status=PostStatus.FAILED`` would otherwise reach the API as
        ``status=PostStatus.FAILED`` instead of ``status=failed``.
        """
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None or v == "":
                continue
            result[to_camel(k)] = v
        return result

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values. Enum members are
        unwrapped to their value so JSON bodies carry e.g. "failed" rather
        than a raw Enum member (plain Enum members are not JSON-serializable).
        """
        from datetime import datetime
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def list_accounts(
        self,
        *,
        profile_id: str | None = None,
        platform: str | None = None,
        status: str | None = None,
        include_over_limit: bool | None = False,
        page: int | None = None,
        limit: int | None = None,
    ) -> dict[str, Any]:
        """List accounts"""
        params = self._build_params(
            profile_id=profile_id,
            platform=platform,
            status=status,
            include_over_limit=include_over_limit,
            page=page,
            limit=limit,
        )
        return self._client._get("/v1/accounts", params=params)

    def get_follower_stats(
        self,
        *,
        account_ids: str | None = None,
        profile_id: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        granularity: str | None = "daily",
    ) -> dict[str, Any]:
        """Get follower stats"""
        params = self._build_params(
            account_ids=account_ids,
            profile_id=profile_id,
            from_date=from_date,
            to_date=to_date,
            granularity=granularity,
        )
        return self._client._get("/v1/accounts/follower-stats", params=params)

    def update_account(
        self,
        account_id: str,
        *,
        username: str | None = None,
        display_name: str | None = None,
        x_capabilities: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Update account"""
        payload = self._build_payload(
            username=username,
            display_name=display_name,
            x_capabilities=x_capabilities,
        )
        return self._client._put(f"/v1/accounts/{account_id}", data=payload)

    def move_account_to_profile(
        self, account_id: str, profile_id: str
    ) -> dict[str, Any]:
        """Move account to another profile"""
        payload = self._build_payload(
            profile_id=profile_id,
        )
        return self._client._patch(f"/v1/accounts/{account_id}", data=payload)

    def delete_account(self, account_id: str) -> dict[str, Any]:
        """Disconnect account"""
        return self._client._delete(f"/v1/accounts/{account_id}")

    def get_all_accounts_health(
        self,
        *,
        profile_id: str | None = None,
        platform: str | None = None,
        status: str | None = None,
    ) -> dict[str, Any]:
        """Check accounts health"""
        params = self._build_params(
            profile_id=profile_id,
            platform=platform,
            status=status,
        )
        return self._client._get("/v1/accounts/health", params=params)

    def get_account_health(self, account_id: str) -> dict[str, Any]:
        """Check account health"""
        return self._client._get(f"/v1/accounts/{account_id}/health")

    def get_instagram_follow_status(
        self, account_id: str, user_id: str, *, refresh: bool | None = None
    ) -> dict[str, Any]:
        """Check whether an Instagram user follows the account"""
        params = self._build_params(
            refresh=refresh,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/follow-status/{user_id}", params=params
        )

    def get_tik_tok_creator_info(
        self, account_id: str, *, media_type: str | None = "video"
    ) -> dict[str, Any]:
        """Get TikTok creator info"""
        params = self._build_params(
            media_type=media_type,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/tiktok/creator-info", params=params
        )

    def get_google_business_reviews(
        self,
        account_id: str,
        *,
        location_id: str | None = None,
        page_size: int | None = 50,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """Get reviews"""
        params = self._build_params(
            location_id=location_id,
            page_size=page_size,
            page_token=page_token,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/gmb-reviews", params=params
        )

    def get_google_business_food_menus(
        self, account_id: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Get food menus"""
        params = self._build_params(
            location_id=location_id,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/gmb-food-menus", params=params
        )

    def update_google_business_food_menus(
        self,
        account_id: str,
        menus: list[Any],
        *,
        location_id: str | None = None,
        update_mask: str | None = None,
    ) -> dict[str, Any]:
        """Update food menus"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            menus=menus,
            update_mask=update_mask,
        )
        return self._client._put(
            f"/v1/accounts/{account_id}/gmb-food-menus", data=payload, params=params
        )

    def get_google_business_location_details(
        self,
        account_id: str,
        *,
        location_id: str | None = None,
        read_mask: str | None = None,
    ) -> dict[str, Any]:
        """Get location details"""
        params = self._build_params(
            location_id=location_id,
            read_mask=read_mask,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/gmb-location-details", params=params
        )

    def update_google_business_location_details(
        self,
        account_id: str,
        update_mask: str,
        *,
        location_id: str | None = None,
        regular_hours: dict[str, Any] | None = None,
        special_hours: dict[str, Any] | None = None,
        profile: dict[str, Any] | None = None,
        website_uri: str | None = None,
        phone_numbers: dict[str, Any] | None = None,
        categories: dict[str, Any] | None = None,
        service_items: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Update location details"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            update_mask=update_mask,
            regular_hours=regular_hours,
            special_hours=special_hours,
            profile=profile,
            website_uri=website_uri,
            phone_numbers=phone_numbers,
            categories=categories,
            service_items=service_items,
        )
        return self._client._put(
            f"/v1/accounts/{account_id}/gmb-location-details",
            data=payload,
            params=params,
        )

    def list_google_business_media(
        self,
        account_id: str,
        *,
        location_id: str | None = None,
        page_size: int | None = 100,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """List media"""
        params = self._build_params(
            location_id=location_id,
            page_size=page_size,
            page_token=page_token,
        )
        return self._client._get(f"/v1/accounts/{account_id}/gmb-media", params=params)

    def create_google_business_media(
        self,
        account_id: str,
        source_url: str,
        *,
        location_id: str | None = None,
        media_format: str | None = "PHOTO",
        description: str | None = None,
        category: str | None = None,
    ) -> dict[str, Any]:
        """Upload photo"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            source_url=source_url,
            media_format=media_format,
            description=description,
            category=category,
        )
        return self._client._post(
            f"/v1/accounts/{account_id}/gmb-media", data=payload, params=params
        )

    def delete_google_business_media(
        self, account_id: str, media_id: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Delete photo"""
        params = self._build_params(
            location_id=location_id,
            media_id=media_id,
        )
        return self._client._delete(
            f"/v1/accounts/{account_id}/gmb-media", params=params
        )

    def get_gmb_attribute_metadata(
        self,
        account_id: str,
        *,
        location_id: str | None = None,
        category_name: str | None = None,
        region_code: str | None = None,
        language_code: str | None = None,
        page_size: int | None = None,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """Get attribute metadata"""
        params = self._build_params(
            location_id=location_id,
            category_name=category_name,
            region_code=region_code,
            language_code=language_code,
            page_size=page_size,
            page_token=page_token,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/gmb-attribute-metadata", params=params
        )

    def get_google_business_attributes(
        self, account_id: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Get attributes"""
        params = self._build_params(
            location_id=location_id,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/gmb-attributes", params=params
        )

    def update_google_business_attributes(
        self,
        account_id: str,
        attributes: list[dict[str, Any]],
        attribute_mask: str,
        *,
        location_id: str | None = None,
    ) -> dict[str, Any]:
        """Update attributes"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            attributes=attributes,
            attribute_mask=attribute_mask,
        )
        return self._client._put(
            f"/v1/accounts/{account_id}/gmb-attributes", data=payload, params=params
        )

    def list_google_business_place_actions(
        self,
        account_id: str,
        *,
        location_id: str | None = None,
        page_size: int | None = 100,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """List action links"""
        params = self._build_params(
            location_id=location_id,
            page_size=page_size,
            page_token=page_token,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/gmb-place-actions", params=params
        )

    def create_google_business_place_action(
        self,
        account_id: str,
        uri: str,
        place_action_type: str,
        *,
        location_id: str | None = None,
    ) -> dict[str, Any]:
        """Create action link"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            uri=uri,
            place_action_type=place_action_type,
        )
        return self._client._post(
            f"/v1/accounts/{account_id}/gmb-place-actions", data=payload, params=params
        )

    def delete_google_business_place_action(
        self, account_id: str, name: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Delete action link"""
        params = self._build_params(
            location_id=location_id,
            name=name,
        )
        return self._client._delete(
            f"/v1/accounts/{account_id}/gmb-place-actions", params=params
        )

    def update_google_business_place_action(
        self,
        account_id: str,
        name: str,
        *,
        location_id: str | None = None,
        uri: str | None = None,
        place_action_type: str | None = None,
    ) -> dict[str, Any]:
        """Update action link"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            name=name,
            uri=uri,
            place_action_type=place_action_type,
        )
        return self._client._patch(
            f"/v1/accounts/{account_id}/gmb-place-actions", data=payload, params=params
        )

    def batch_get_google_business_reviews(
        self,
        account_id: str,
        location_names: list[str],
        *,
        page_size: int | None = 50,
        page_token: str | None = None,
        order_by: str | None = "updateTime desc",
    ) -> dict[str, Any]:
        """Batch get reviews"""
        payload = self._build_payload(
            location_names=location_names,
            page_size=page_size,
            page_token=page_token,
            order_by=order_by,
        )
        return self._client._post(
            f"/v1/accounts/{account_id}/gmb-reviews/batch", data=payload
        )

    def get_google_business_review(
        self, account_id: str, review_id: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Get a review"""
        params = self._build_params(
            location_id=location_id,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/gmb-reviews/{review_id}", params=params
        )

    def reply_to_google_business_review(
        self, account_id: str, review_id: str, comment: str
    ) -> dict[str, Any]:
        """Reply to a review"""
        payload = self._build_payload(
            comment=comment,
        )
        return self._client._post(
            f"/v1/accounts/{account_id}/gmb-reviews/{review_id}/reply", data=payload
        )

    def delete_google_business_review_reply(
        self, account_id: str, review_id: str
    ) -> dict[str, Any]:
        """Delete a review reply"""
        return self._client._delete(
            f"/v1/accounts/{account_id}/gmb-reviews/{review_id}/reply"
        )

    def get_linked_in_mentions(
        self, account_id: str, url: str, *, display_name: str | None = None
    ) -> dict[str, Any]:
        """Resolve LinkedIn mention"""
        params = self._build_params(
            url=url,
            display_name=display_name,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/linkedin-mentions", params=params
        )

    def get_slack_settings(self, account_id: str) -> dict[str, Any]:
        """Get Slack account settings"""
        return self._client._get(f"/v1/accounts/{account_id}/slack-settings")

    def update_slack_settings(
        self,
        account_id: str,
        *,
        default_username: str | None = None,
        default_icon_url: str | None = None,
    ) -> dict[str, Any]:
        """Update Slack account settings"""
        payload = self._build_payload(
            default_username=default_username,
            default_icon_url=default_icon_url,
        )
        return self._client._patch(
            f"/v1/accounts/{account_id}/slack-settings", data=payload
        )

    def get_bluesky_settings(self, account_id: str) -> dict[str, Any]:
        """Get Bluesky account settings"""
        return self._client._get(f"/v1/accounts/{account_id}/bluesky-settings")

    def update_bluesky_settings(
        self, account_id: str, default_langs: Any
    ) -> dict[str, Any]:
        """Update Bluesky account settings"""
        payload = self._build_payload(
            default_langs=default_langs,
        )
        return self._client._patch(
            f"/v1/accounts/{account_id}/bluesky-settings", data=payload
        )

    async def alist_accounts(
        self,
        *,
        profile_id: str | None = None,
        platform: str | None = None,
        status: str | None = None,
        include_over_limit: bool | None = False,
        page: int | None = None,
        limit: int | None = None,
    ) -> dict[str, Any]:
        """List accounts (async)"""
        params = self._build_params(
            profile_id=profile_id,
            platform=platform,
            status=status,
            include_over_limit=include_over_limit,
            page=page,
            limit=limit,
        )
        return await self._client._aget("/v1/accounts", params=params)

    async def aget_follower_stats(
        self,
        *,
        account_ids: str | None = None,
        profile_id: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        granularity: str | None = "daily",
    ) -> dict[str, Any]:
        """Get follower stats (async)"""
        params = self._build_params(
            account_ids=account_ids,
            profile_id=profile_id,
            from_date=from_date,
            to_date=to_date,
            granularity=granularity,
        )
        return await self._client._aget("/v1/accounts/follower-stats", params=params)

    async def aupdate_account(
        self,
        account_id: str,
        *,
        username: str | None = None,
        display_name: str | None = None,
        x_capabilities: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Update account (async)"""
        payload = self._build_payload(
            username=username,
            display_name=display_name,
            x_capabilities=x_capabilities,
        )
        return await self._client._aput(f"/v1/accounts/{account_id}", data=payload)

    async def amove_account_to_profile(
        self, account_id: str, profile_id: str
    ) -> dict[str, Any]:
        """Move account to another profile (async)"""
        payload = self._build_payload(
            profile_id=profile_id,
        )
        return await self._client._apatch(f"/v1/accounts/{account_id}", data=payload)

    async def adelete_account(self, account_id: str) -> dict[str, Any]:
        """Disconnect account (async)"""
        return await self._client._adelete(f"/v1/accounts/{account_id}")

    async def aget_all_accounts_health(
        self,
        *,
        profile_id: str | None = None,
        platform: str | None = None,
        status: str | None = None,
    ) -> dict[str, Any]:
        """Check accounts health (async)"""
        params = self._build_params(
            profile_id=profile_id,
            platform=platform,
            status=status,
        )
        return await self._client._aget("/v1/accounts/health", params=params)

    async def aget_account_health(self, account_id: str) -> dict[str, Any]:
        """Check account health (async)"""
        return await self._client._aget(f"/v1/accounts/{account_id}/health")

    async def aget_instagram_follow_status(
        self, account_id: str, user_id: str, *, refresh: bool | None = None
    ) -> dict[str, Any]:
        """Check whether an Instagram user follows the account (async)"""
        params = self._build_params(
            refresh=refresh,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/follow-status/{user_id}", params=params
        )

    async def aget_tik_tok_creator_info(
        self, account_id: str, *, media_type: str | None = "video"
    ) -> dict[str, Any]:
        """Get TikTok creator info (async)"""
        params = self._build_params(
            media_type=media_type,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/tiktok/creator-info", params=params
        )

    async def aget_google_business_reviews(
        self,
        account_id: str,
        *,
        location_id: str | None = None,
        page_size: int | None = 50,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """Get reviews (async)"""
        params = self._build_params(
            location_id=location_id,
            page_size=page_size,
            page_token=page_token,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/gmb-reviews", params=params
        )

    async def aget_google_business_food_menus(
        self, account_id: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Get food menus (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/gmb-food-menus", params=params
        )

    async def aupdate_google_business_food_menus(
        self,
        account_id: str,
        menus: list[Any],
        *,
        location_id: str | None = None,
        update_mask: str | None = None,
    ) -> dict[str, Any]:
        """Update food menus (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            menus=menus,
            update_mask=update_mask,
        )
        return await self._client._aput(
            f"/v1/accounts/{account_id}/gmb-food-menus", data=payload, params=params
        )

    async def aget_google_business_location_details(
        self,
        account_id: str,
        *,
        location_id: str | None = None,
        read_mask: str | None = None,
    ) -> dict[str, Any]:
        """Get location details (async)"""
        params = self._build_params(
            location_id=location_id,
            read_mask=read_mask,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/gmb-location-details", params=params
        )

    async def aupdate_google_business_location_details(
        self,
        account_id: str,
        update_mask: str,
        *,
        location_id: str | None = None,
        regular_hours: dict[str, Any] | None = None,
        special_hours: dict[str, Any] | None = None,
        profile: dict[str, Any] | None = None,
        website_uri: str | None = None,
        phone_numbers: dict[str, Any] | None = None,
        categories: dict[str, Any] | None = None,
        service_items: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Update location details (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            update_mask=update_mask,
            regular_hours=regular_hours,
            special_hours=special_hours,
            profile=profile,
            website_uri=website_uri,
            phone_numbers=phone_numbers,
            categories=categories,
            service_items=service_items,
        )
        return await self._client._aput(
            f"/v1/accounts/{account_id}/gmb-location-details",
            data=payload,
            params=params,
        )

    async def alist_google_business_media(
        self,
        account_id: str,
        *,
        location_id: str | None = None,
        page_size: int | None = 100,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """List media (async)"""
        params = self._build_params(
            location_id=location_id,
            page_size=page_size,
            page_token=page_token,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/gmb-media", params=params
        )

    async def acreate_google_business_media(
        self,
        account_id: str,
        source_url: str,
        *,
        location_id: str | None = None,
        media_format: str | None = "PHOTO",
        description: str | None = None,
        category: str | None = None,
    ) -> dict[str, Any]:
        """Upload photo (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            source_url=source_url,
            media_format=media_format,
            description=description,
            category=category,
        )
        return await self._client._apost(
            f"/v1/accounts/{account_id}/gmb-media", data=payload, params=params
        )

    async def adelete_google_business_media(
        self, account_id: str, media_id: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Delete photo (async)"""
        params = self._build_params(
            location_id=location_id,
            media_id=media_id,
        )
        return await self._client._adelete(
            f"/v1/accounts/{account_id}/gmb-media", params=params
        )

    async def aget_gmb_attribute_metadata(
        self,
        account_id: str,
        *,
        location_id: str | None = None,
        category_name: str | None = None,
        region_code: str | None = None,
        language_code: str | None = None,
        page_size: int | None = None,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """Get attribute metadata (async)"""
        params = self._build_params(
            location_id=location_id,
            category_name=category_name,
            region_code=region_code,
            language_code=language_code,
            page_size=page_size,
            page_token=page_token,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/gmb-attribute-metadata", params=params
        )

    async def aget_google_business_attributes(
        self, account_id: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Get attributes (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/gmb-attributes", params=params
        )

    async def aupdate_google_business_attributes(
        self,
        account_id: str,
        attributes: list[dict[str, Any]],
        attribute_mask: str,
        *,
        location_id: str | None = None,
    ) -> dict[str, Any]:
        """Update attributes (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            attributes=attributes,
            attribute_mask=attribute_mask,
        )
        return await self._client._aput(
            f"/v1/accounts/{account_id}/gmb-attributes", data=payload, params=params
        )

    async def alist_google_business_place_actions(
        self,
        account_id: str,
        *,
        location_id: str | None = None,
        page_size: int | None = 100,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """List action links (async)"""
        params = self._build_params(
            location_id=location_id,
            page_size=page_size,
            page_token=page_token,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/gmb-place-actions", params=params
        )

    async def acreate_google_business_place_action(
        self,
        account_id: str,
        uri: str,
        place_action_type: str,
        *,
        location_id: str | None = None,
    ) -> dict[str, Any]:
        """Create action link (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            uri=uri,
            place_action_type=place_action_type,
        )
        return await self._client._apost(
            f"/v1/accounts/{account_id}/gmb-place-actions", data=payload, params=params
        )

    async def adelete_google_business_place_action(
        self, account_id: str, name: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Delete action link (async)"""
        params = self._build_params(
            location_id=location_id,
            name=name,
        )
        return await self._client._adelete(
            f"/v1/accounts/{account_id}/gmb-place-actions", params=params
        )

    async def aupdate_google_business_place_action(
        self,
        account_id: str,
        name: str,
        *,
        location_id: str | None = None,
        uri: str | None = None,
        place_action_type: str | None = None,
    ) -> dict[str, Any]:
        """Update action link (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            name=name,
            uri=uri,
            place_action_type=place_action_type,
        )
        return await self._client._apatch(
            f"/v1/accounts/{account_id}/gmb-place-actions", data=payload, params=params
        )

    async def abatch_get_google_business_reviews(
        self,
        account_id: str,
        location_names: list[str],
        *,
        page_size: int | None = 50,
        page_token: str | None = None,
        order_by: str | None = "updateTime desc",
    ) -> dict[str, Any]:
        """Batch get reviews (async)"""
        payload = self._build_payload(
            location_names=location_names,
            page_size=page_size,
            page_token=page_token,
            order_by=order_by,
        )
        return await self._client._apost(
            f"/v1/accounts/{account_id}/gmb-reviews/batch", data=payload
        )

    async def aget_google_business_review(
        self, account_id: str, review_id: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Get a review (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/gmb-reviews/{review_id}", params=params
        )

    async def areply_to_google_business_review(
        self, account_id: str, review_id: str, comment: str
    ) -> dict[str, Any]:
        """Reply to a review (async)"""
        payload = self._build_payload(
            comment=comment,
        )
        return await self._client._apost(
            f"/v1/accounts/{account_id}/gmb-reviews/{review_id}/reply", data=payload
        )

    async def adelete_google_business_review_reply(
        self, account_id: str, review_id: str
    ) -> dict[str, Any]:
        """Delete a review reply (async)"""
        return await self._client._adelete(
            f"/v1/accounts/{account_id}/gmb-reviews/{review_id}/reply"
        )

    async def aget_linked_in_mentions(
        self, account_id: str, url: str, *, display_name: str | None = None
    ) -> dict[str, Any]:
        """Resolve LinkedIn mention (async)"""
        params = self._build_params(
            url=url,
            display_name=display_name,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/linkedin-mentions", params=params
        )

    async def aget_slack_settings(self, account_id: str) -> dict[str, Any]:
        """Get Slack account settings (async)"""
        return await self._client._aget(f"/v1/accounts/{account_id}/slack-settings")

    async def aupdate_slack_settings(
        self,
        account_id: str,
        *,
        default_username: str | None = None,
        default_icon_url: str | None = None,
    ) -> dict[str, Any]:
        """Update Slack account settings (async)"""
        payload = self._build_payload(
            default_username=default_username,
            default_icon_url=default_icon_url,
        )
        return await self._client._apatch(
            f"/v1/accounts/{account_id}/slack-settings", data=payload
        )

    async def aget_bluesky_settings(self, account_id: str) -> dict[str, Any]:
        """Get Bluesky account settings (async)"""
        return await self._client._aget(f"/v1/accounts/{account_id}/bluesky-settings")

    async def aupdate_bluesky_settings(
        self, account_id: str, default_langs: Any
    ) -> dict[str, Any]:
        """Update Bluesky account settings (async)"""
        payload = self._build_payload(
            default_langs=default_langs,
        )
        return await self._client._apatch(
            f"/v1/accounts/{account_id}/bluesky-settings", data=payload
        )
