"""
Auto-generated ad_accounts resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class AdAccountsResource:
    """
    ad_accounts operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.

        Enum members are unwrapped to their value: httpx serializes params
        via str(), which yields "ClassName.MEMBER" for Enum members, so
        e.g. ``status=PostStatus.FAILED`` would otherwise reach the API as
        ``status=PostStatus.FAILED`` instead of ``status=failed``.
        """
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None or v == "":
                continue
            result[to_camel(k)] = v
        return result

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values. Enum members are
        unwrapped to their value so JSON bodies carry e.g. "failed" rather
        than a raw Enum member (plain Enum members are not JSON-serializable).
        """
        from datetime import datetime
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def get_ad_comments(
        self,
        ad_id: str,
        *,
        placement: str | None = None,
        limit: int | None = 25,
        since: str | None = None,
        until: str | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """List comments on an ad"""
        params = self._build_params(
            placement=placement,
            limit=limit,
            since=since,
            until=until,
            cursor=cursor,
        )
        return self._client._get(f"/v1/ads/{ad_id}/comments", params=params)

    def reply_to_ad_comment(
        self,
        ad_id: str,
        comment_id: str,
        text: str,
        *,
        since: str | None = None,
        until: str | None = None,
    ) -> dict[str, Any]:
        """Reply to an ad comment"""
        params = self._build_params(
            since=since,
            until=until,
        )
        payload = self._build_payload(
            text=text,
        )
        return self._client._post(
            f"/v1/ads/{ad_id}/comments/{comment_id}/reply", data=payload, params=params
        )

    def hide_ad_comment(
        self,
        ad_id: str,
        comment_id: str,
        hidden: bool,
        *,
        since: str | None = None,
        until: str | None = None,
    ) -> dict[str, Any]:
        """Hide or unhide an ad comment"""
        params = self._build_params(
            since=since,
            until=until,
        )
        payload = self._build_payload(
            hidden=hidden,
        )
        return self._client._post(
            f"/v1/ads/{ad_id}/comments/{comment_id}/hide", data=payload, params=params
        )

    def delete_ad_comment(
        self,
        ad_id: str,
        comment_id: str,
        *,
        since: str | None = None,
        until: str | None = None,
    ) -> dict[str, Any]:
        """Delete an ad comment"""
        params = self._build_params(
            since=since,
            until=until,
        )
        return self._client._delete(
            f"/v1/ads/{ad_id}/comments/{comment_id}", params=params
        )

    def list_ads_business_centers(self, account_id: str) -> dict[str, Any]:
        """List TikTok Business Centers"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get("/v1/ads/business-centers", params=params)

    def get_ads_activity_log(
        self,
        account_id: str,
        ad_account_id: str,
        *,
        since: str | None = None,
        until: str | None = None,
        object_id: str | None = None,
        limit: int | None = 50,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Ad account change / audit log"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            since=since,
            until=until,
            object_id=object_id,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/ads/activity", params=params)

    def list_ad_studies(
        self,
        account_id: str,
        ad_account_id: str,
        *,
        fields: str | None = None,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """A/B tests and lift studies"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            fields=fields,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/ads/studies", params=params)

    def list_ads_instagram_accounts(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """List Instagram ad identities"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
        )
        return self._client._get("/v1/ads/instagram-accounts", params=params)

    def list_ads_instagram_posts(
        self,
        account_id: str,
        *,
        ad_account_id: str | None = None,
        ig_user_id: str | None = None,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """List Instagram posts to boost"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            ig_user_id=ig_user_id,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/ads/instagram-posts", params=params)

    def list_advertisable_applications(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """List advertisable apps"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
        )
        return self._client._get("/v1/ads/advertisable-applications", params=params)

    def get_ios_fourteen_campaign_limits(
        self, account_id: str, ad_account_id: str, application_id: str
    ) -> dict[str, Any]:
        """Get iOS 14 campaign limits"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            application_id=application_id,
        )
        return self._client._get("/v1/ads/ios-fourteen-campaign-limits", params=params)

    def list_meta_businesses(
        self, account_id: str, *, limit: int | None = 25, after: str | None = None
    ) -> dict[str, Any]:
        """Businesses list"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/ads/businesses", params=params)

    def list_ad_labels(
        self,
        account_id: str,
        ad_account_id: str,
        *,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Ad labels"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/ads/labels", params=params)

    def list_high_demand_periods(
        self,
        account_id: str,
        *,
        campaign_id: str | None = None,
        ad_set_id: str | None = None,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """List high-demand periods"""
        params = self._build_params(
            account_id=account_id,
            campaign_id=campaign_id,
            ad_set_id=ad_set_id,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/ads/high-demand-periods", params=params)

    def create_high_demand_period(
        self,
        account_id: str,
        budget_value: float,
        budget_value_type: str,
        time_start: int,
        time_end: int,
        *,
        campaign_id: str | None = None,
        ad_set_id: str | None = None,
        recurrence_type: str | None = None,
        currency: str | None = None,
    ) -> dict[str, Any]:
        """Schedule a budget increase"""
        payload = self._build_payload(
            account_id=account_id,
            campaign_id=campaign_id,
            ad_set_id=ad_set_id,
            budget_value=budget_value,
            budget_value_type=budget_value_type,
            time_start=time_start,
            time_end=time_end,
            recurrence_type=recurrence_type,
            currency=currency,
        )
        return self._client._post("/v1/ads/high-demand-periods", data=payload)

    def list_value_rule_sets(
        self,
        account_id: str,
        ad_account_id: str,
        *,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """List value rule sets"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/ads/value-rule-sets", params=params)

    def create_value_rule_set(
        self, account_id: str, ad_account_id: str, name: str, rules: list[Any]
    ) -> dict[str, Any]:
        """Create a value rule set"""
        payload = self._build_payload(
            account_id=account_id,
            ad_account_id=ad_account_id,
            name=name,
            rules=rules,
        )
        return self._client._post("/v1/ads/value-rule-sets", data=payload)

    def get_value_rule_set(
        self, value_rule_set_id: str, account_id: str
    ) -> dict[str, Any]:
        """Read a value rule set"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get(
            f"/v1/ads/value-rule-sets/{value_rule_set_id}", params=params
        )

    def update_value_rule_set(
        self, value_rule_set_id: str, account_id: str, name: str, rules: list[Any]
    ) -> dict[str, Any]:
        """Replace a value rule set"""
        payload = self._build_payload(
            account_id=account_id,
            name=name,
            rules=rules,
        )
        return self._client._put(
            f"/v1/ads/value-rule-sets/{value_rule_set_id}", data=payload
        )

    def delete_value_rule_set(
        self, value_rule_set_id: str, account_id: str
    ) -> dict[str, Any]:
        """Delete a value rule set"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._delete(
            f"/v1/ads/value-rule-sets/{value_rule_set_id}", params=params
        )

    def list_ad_negative_keyword_lists(
        self,
        account_id: str,
        *,
        customer_id: str | None = None,
        platform: str | None = None,
    ) -> dict[str, Any]:
        """List negative keyword lists"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
        )
        return self._client._get(
            "/v1/ads/accounts/negative-keyword-lists", params=params
        )

    def create_ad_negative_keyword_list(
        self,
        account_id: str,
        name: str,
        *,
        customer_id: str | None = None,
        platform: str | None = None,
        keywords: list[Any] | None = None,
    ) -> dict[str, Any]:
        """Create a negative keyword list"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
            name=name,
            keywords=keywords,
        )
        return self._client._post(
            "/v1/ads/accounts/negative-keyword-lists", data=payload
        )

    def get_ad_negative_keyword_list(
        self,
        list_id: str,
        account_id: str,
        *,
        customer_id: str | None = None,
        platform: str | None = None,
    ) -> dict[str, Any]:
        """Get a negative keyword list"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
        )
        return self._client._get(
            f"/v1/ads/accounts/negative-keyword-lists/{list_id}", params=params
        )

    def update_ad_negative_keyword_list(
        self,
        list_id: str,
        account_id: str,
        name: str,
        *,
        customer_id: str | None = None,
        platform: str | None = None,
    ) -> dict[str, Any]:
        """Rename a negative keyword list"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
            name=name,
        )
        return self._client._put(
            f"/v1/ads/accounts/negative-keyword-lists/{list_id}", data=payload
        )

    def delete_ad_negative_keyword_list(
        self,
        list_id: str,
        account_id: str,
        *,
        customer_id: str | None = None,
        platform: str | None = None,
    ) -> dict[str, Any]:
        """Delete a negative keyword list"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
        )
        return self._client._delete(
            f"/v1/ads/accounts/negative-keyword-lists/{list_id}", params=params
        )

    def replace_ad_negative_keyword_list_keywords(
        self,
        list_id: str,
        account_id: str,
        keywords: list[Any],
        *,
        customer_id: str | None = None,
        platform: str | None = None,
    ) -> dict[str, Any]:
        """Replace negative list keywords"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
            keywords=keywords,
        )
        return self._client._put(
            f"/v1/ads/accounts/negative-keyword-lists/{list_id}/keywords", data=payload
        )

    def list_account_callouts(
        self, account_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """List account callouts"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
        )
        return self._client._get("/v1/ads/accounts/callouts", params=params)

    def add_account_callouts(
        self, account_id: str, callouts: list[str], *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """Add account callouts"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            callouts=callouts,
        )
        return self._client._post("/v1/ads/accounts/callouts", data=payload)

    def update_account_callouts(
        self,
        account_id: str,
        updates: list[dict[str, Any]],
        *,
        customer_id: str | None = None,
    ) -> dict[str, Any]:
        """Update account callouts"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            updates=updates,
        )
        return self._client._put("/v1/ads/accounts/callouts", data=payload)

    def remove_account_callout(
        self, account_id: str, asset_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """Remove account callout"""
        return self._client._delete("/v1/ads/accounts/callouts")

    def list_account_sitelinks(
        self, account_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """List account sitelinks"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
        )
        return self._client._get("/v1/ads/accounts/sitelinks", params=params)

    def add_account_sitelinks(
        self, account_id: str, sitelinks: list[Any], *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """Add account sitelinks"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            sitelinks=sitelinks,
        )
        return self._client._post("/v1/ads/accounts/sitelinks", data=payload)

    def update_account_sitelinks(
        self,
        account_id: str,
        updates: list[dict[str, Any]],
        *,
        customer_id: str | None = None,
    ) -> dict[str, Any]:
        """Update account sitelinks"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            updates=updates,
        )
        return self._client._put("/v1/ads/accounts/sitelinks", data=payload)

    def remove_account_sitelink(
        self, account_id: str, asset_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """Remove account sitelink"""
        return self._client._delete("/v1/ads/accounts/sitelinks")

    def list_account_structured_snippets(
        self, account_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """List account snippets"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
        )
        return self._client._get("/v1/ads/accounts/structured-snippets", params=params)

    def add_account_structured_snippets(
        self,
        account_id: str,
        structured_snippets: list[Any],
        *,
        customer_id: str | None = None,
    ) -> dict[str, Any]:
        """Add account snippets"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            structured_snippets=structured_snippets,
        )
        return self._client._post("/v1/ads/accounts/structured-snippets", data=payload)

    def update_account_structured_snippets(
        self,
        account_id: str,
        updates: list[dict[str, Any]],
        *,
        customer_id: str | None = None,
    ) -> dict[str, Any]:
        """Update account snippets"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            updates=updates,
        )
        return self._client._put("/v1/ads/accounts/structured-snippets", data=payload)

    def remove_account_structured_snippet(
        self, account_id: str, asset_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """Remove account snippet"""
        return self._client._delete("/v1/ads/accounts/structured-snippets")

    def get_ad_account_finance(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """Ad account finances"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
        )
        return self._client._get("/v1/ads/accounts/finance", params=params)

    def create_ad_account(
        self,
        account_id: str,
        business_id: str,
        name: str,
        currency: str,
        timezone_id: int,
        *,
        end_advertiser: str | None = "NONE",
        media_agency: str | None = "NONE",
        partner: str | None = "NONE",
        invoice: bool | None = None,
        invoice_group_id: str | None = None,
        invoicing_emails: list[str] | None = None,
        io: bool | None = None,
        po_number: str | None = None,
        funding_id: str | None = None,
        ad_account_created_from_bm_flag: bool | None = None,
    ) -> dict[str, Any]:
        """Create Meta ad account"""
        payload = self._build_payload(
            account_id=account_id,
            business_id=business_id,
            name=name,
            currency=currency,
            timezone_id=timezone_id,
            end_advertiser=end_advertiser,
            media_agency=media_agency,
            partner=partner,
            invoice=invoice,
            invoice_group_id=invoice_group_id,
            invoicing_emails=invoicing_emails,
            io=io,
            po_number=po_number,
            funding_id=funding_id,
            ad_account_created_from_bm_flag=ad_account_created_from_bm_flag,
        )
        return self._client._post("/v1/ads/accounts", data=payload)

    def list_ad_accounts(
        self,
        account_id: str,
        *,
        ad_account_id: str | None = None,
        limit: int | None = None,
    ) -> dict[str, Any]:
        """List ad accounts"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            limit=limit,
        )
        return self._client._get("/v1/ads/accounts", params=params)

    def update_ad_account(
        self,
        account_id: str,
        ad_account_id: str,
        default_dsa_beneficiary: str,
        *,
        default_dsa_payor: str | None = None,
    ) -> dict[str, Any]:
        """Update ad account settings"""
        payload = self._build_payload(
            account_id=account_id,
            ad_account_id=ad_account_id,
            default_dsa_beneficiary=default_dsa_beneficiary,
            default_dsa_payor=default_dsa_payor,
        )
        return self._client._patch("/v1/ads/accounts", data=payload)

    def get_dsa_defaults(self, account_id: str, ad_account_id: str) -> dict[str, Any]:
        """Get ad account DSA defaults"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
        )
        return self._client._get("/v1/ads/dsa-defaults", params=params)

    def get_dsa_recommendations(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """Get DSA recommendations"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
        )
        return self._client._get("/v1/ads/dsa-recommendations", params=params)

    def list_custom_conversions(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """List custom conversions"""
        params = self._build_params(
            ad_account_id=ad_account_id,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/custom-conversions", params=params
        )

    def create_custom_conversion(
        self,
        account_id: str,
        ad_account_id: str,
        name: str,
        pixel_id: str,
        custom_event_type: str,
        rule: dict[str, Any],
    ) -> dict[str, Any]:
        """Create custom conversion"""
        payload = self._build_payload(
            ad_account_id=ad_account_id,
            name=name,
            pixel_id=pixel_id,
            custom_event_type=custom_event_type,
            rule=rule,
        )
        return self._client._post(
            f"/v1/accounts/{account_id}/custom-conversions", data=payload
        )

    def list_tik_tok_ad_pixels(
        self,
        account_id: str,
        *,
        advertiser_id: str | None = None,
        code: str | None = None,
    ) -> dict[str, Any]:
        """List TikTok ad pixels"""
        params = self._build_params(
            account_id=account_id,
            advertiser_id=advertiser_id,
            code=code,
        )
        return self._client._get("/v1/ads/pixels", params=params)

    async def aget_ad_comments(
        self,
        ad_id: str,
        *,
        placement: str | None = None,
        limit: int | None = 25,
        since: str | None = None,
        until: str | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """List comments on an ad (async)"""
        params = self._build_params(
            placement=placement,
            limit=limit,
            since=since,
            until=until,
            cursor=cursor,
        )
        return await self._client._aget(f"/v1/ads/{ad_id}/comments", params=params)

    async def areply_to_ad_comment(
        self,
        ad_id: str,
        comment_id: str,
        text: str,
        *,
        since: str | None = None,
        until: str | None = None,
    ) -> dict[str, Any]:
        """Reply to an ad comment (async)"""
        params = self._build_params(
            since=since,
            until=until,
        )
        payload = self._build_payload(
            text=text,
        )
        return await self._client._apost(
            f"/v1/ads/{ad_id}/comments/{comment_id}/reply", data=payload, params=params
        )

    async def ahide_ad_comment(
        self,
        ad_id: str,
        comment_id: str,
        hidden: bool,
        *,
        since: str | None = None,
        until: str | None = None,
    ) -> dict[str, Any]:
        """Hide or unhide an ad comment (async)"""
        params = self._build_params(
            since=since,
            until=until,
        )
        payload = self._build_payload(
            hidden=hidden,
        )
        return await self._client._apost(
            f"/v1/ads/{ad_id}/comments/{comment_id}/hide", data=payload, params=params
        )

    async def adelete_ad_comment(
        self,
        ad_id: str,
        comment_id: str,
        *,
        since: str | None = None,
        until: str | None = None,
    ) -> dict[str, Any]:
        """Delete an ad comment (async)"""
        params = self._build_params(
            since=since,
            until=until,
        )
        return await self._client._adelete(
            f"/v1/ads/{ad_id}/comments/{comment_id}", params=params
        )

    async def alist_ads_business_centers(self, account_id: str) -> dict[str, Any]:
        """List TikTok Business Centers (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget("/v1/ads/business-centers", params=params)

    async def aget_ads_activity_log(
        self,
        account_id: str,
        ad_account_id: str,
        *,
        since: str | None = None,
        until: str | None = None,
        object_id: str | None = None,
        limit: int | None = 50,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Ad account change / audit log (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            since=since,
            until=until,
            object_id=object_id,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/ads/activity", params=params)

    async def alist_ad_studies(
        self,
        account_id: str,
        ad_account_id: str,
        *,
        fields: str | None = None,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """A/B tests and lift studies (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            fields=fields,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/ads/studies", params=params)

    async def alist_ads_instagram_accounts(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """List Instagram ad identities (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
        )
        return await self._client._aget("/v1/ads/instagram-accounts", params=params)

    async def alist_ads_instagram_posts(
        self,
        account_id: str,
        *,
        ad_account_id: str | None = None,
        ig_user_id: str | None = None,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """List Instagram posts to boost (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            ig_user_id=ig_user_id,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/ads/instagram-posts", params=params)

    async def alist_advertisable_applications(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """List advertisable apps (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
        )
        return await self._client._aget(
            "/v1/ads/advertisable-applications", params=params
        )

    async def aget_ios_fourteen_campaign_limits(
        self, account_id: str, ad_account_id: str, application_id: str
    ) -> dict[str, Any]:
        """Get iOS 14 campaign limits (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            application_id=application_id,
        )
        return await self._client._aget(
            "/v1/ads/ios-fourteen-campaign-limits", params=params
        )

    async def alist_meta_businesses(
        self, account_id: str, *, limit: int | None = 25, after: str | None = None
    ) -> dict[str, Any]:
        """Businesses list (async)"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/ads/businesses", params=params)

    async def alist_ad_labels(
        self,
        account_id: str,
        ad_account_id: str,
        *,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Ad labels (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/ads/labels", params=params)

    async def alist_high_demand_periods(
        self,
        account_id: str,
        *,
        campaign_id: str | None = None,
        ad_set_id: str | None = None,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """List high-demand periods (async)"""
        params = self._build_params(
            account_id=account_id,
            campaign_id=campaign_id,
            ad_set_id=ad_set_id,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/ads/high-demand-periods", params=params)

    async def acreate_high_demand_period(
        self,
        account_id: str,
        budget_value: float,
        budget_value_type: str,
        time_start: int,
        time_end: int,
        *,
        campaign_id: str | None = None,
        ad_set_id: str | None = None,
        recurrence_type: str | None = None,
        currency: str | None = None,
    ) -> dict[str, Any]:
        """Schedule a budget increase (async)"""
        payload = self._build_payload(
            account_id=account_id,
            campaign_id=campaign_id,
            ad_set_id=ad_set_id,
            budget_value=budget_value,
            budget_value_type=budget_value_type,
            time_start=time_start,
            time_end=time_end,
            recurrence_type=recurrence_type,
            currency=currency,
        )
        return await self._client._apost("/v1/ads/high-demand-periods", data=payload)

    async def alist_value_rule_sets(
        self,
        account_id: str,
        ad_account_id: str,
        *,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """List value rule sets (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/ads/value-rule-sets", params=params)

    async def acreate_value_rule_set(
        self, account_id: str, ad_account_id: str, name: str, rules: list[Any]
    ) -> dict[str, Any]:
        """Create a value rule set (async)"""
        payload = self._build_payload(
            account_id=account_id,
            ad_account_id=ad_account_id,
            name=name,
            rules=rules,
        )
        return await self._client._apost("/v1/ads/value-rule-sets", data=payload)

    async def aget_value_rule_set(
        self, value_rule_set_id: str, account_id: str
    ) -> dict[str, Any]:
        """Read a value rule set (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget(
            f"/v1/ads/value-rule-sets/{value_rule_set_id}", params=params
        )

    async def aupdate_value_rule_set(
        self, value_rule_set_id: str, account_id: str, name: str, rules: list[Any]
    ) -> dict[str, Any]:
        """Replace a value rule set (async)"""
        payload = self._build_payload(
            account_id=account_id,
            name=name,
            rules=rules,
        )
        return await self._client._aput(
            f"/v1/ads/value-rule-sets/{value_rule_set_id}", data=payload
        )

    async def adelete_value_rule_set(
        self, value_rule_set_id: str, account_id: str
    ) -> dict[str, Any]:
        """Delete a value rule set (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._adelete(
            f"/v1/ads/value-rule-sets/{value_rule_set_id}", params=params
        )

    async def alist_ad_negative_keyword_lists(
        self,
        account_id: str,
        *,
        customer_id: str | None = None,
        platform: str | None = None,
    ) -> dict[str, Any]:
        """List negative keyword lists (async)"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
        )
        return await self._client._aget(
            "/v1/ads/accounts/negative-keyword-lists", params=params
        )

    async def acreate_ad_negative_keyword_list(
        self,
        account_id: str,
        name: str,
        *,
        customer_id: str | None = None,
        platform: str | None = None,
        keywords: list[Any] | None = None,
    ) -> dict[str, Any]:
        """Create a negative keyword list (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
            name=name,
            keywords=keywords,
        )
        return await self._client._apost(
            "/v1/ads/accounts/negative-keyword-lists", data=payload
        )

    async def aget_ad_negative_keyword_list(
        self,
        list_id: str,
        account_id: str,
        *,
        customer_id: str | None = None,
        platform: str | None = None,
    ) -> dict[str, Any]:
        """Get a negative keyword list (async)"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
        )
        return await self._client._aget(
            f"/v1/ads/accounts/negative-keyword-lists/{list_id}", params=params
        )

    async def aupdate_ad_negative_keyword_list(
        self,
        list_id: str,
        account_id: str,
        name: str,
        *,
        customer_id: str | None = None,
        platform: str | None = None,
    ) -> dict[str, Any]:
        """Rename a negative keyword list (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
            name=name,
        )
        return await self._client._aput(
            f"/v1/ads/accounts/negative-keyword-lists/{list_id}", data=payload
        )

    async def adelete_ad_negative_keyword_list(
        self,
        list_id: str,
        account_id: str,
        *,
        customer_id: str | None = None,
        platform: str | None = None,
    ) -> dict[str, Any]:
        """Delete a negative keyword list (async)"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
        )
        return await self._client._adelete(
            f"/v1/ads/accounts/negative-keyword-lists/{list_id}", params=params
        )

    async def areplace_ad_negative_keyword_list_keywords(
        self,
        list_id: str,
        account_id: str,
        keywords: list[Any],
        *,
        customer_id: str | None = None,
        platform: str | None = None,
    ) -> dict[str, Any]:
        """Replace negative list keywords (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            platform=platform,
            keywords=keywords,
        )
        return await self._client._aput(
            f"/v1/ads/accounts/negative-keyword-lists/{list_id}/keywords", data=payload
        )

    async def alist_account_callouts(
        self, account_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """List account callouts (async)"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
        )
        return await self._client._aget("/v1/ads/accounts/callouts", params=params)

    async def aadd_account_callouts(
        self, account_id: str, callouts: list[str], *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """Add account callouts (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            callouts=callouts,
        )
        return await self._client._apost("/v1/ads/accounts/callouts", data=payload)

    async def aupdate_account_callouts(
        self,
        account_id: str,
        updates: list[dict[str, Any]],
        *,
        customer_id: str | None = None,
    ) -> dict[str, Any]:
        """Update account callouts (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            updates=updates,
        )
        return await self._client._aput("/v1/ads/accounts/callouts", data=payload)

    async def aremove_account_callout(
        self, account_id: str, asset_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """Remove account callout (async)"""
        return await self._client._adelete("/v1/ads/accounts/callouts")

    async def alist_account_sitelinks(
        self, account_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """List account sitelinks (async)"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
        )
        return await self._client._aget("/v1/ads/accounts/sitelinks", params=params)

    async def aadd_account_sitelinks(
        self, account_id: str, sitelinks: list[Any], *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """Add account sitelinks (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            sitelinks=sitelinks,
        )
        return await self._client._apost("/v1/ads/accounts/sitelinks", data=payload)

    async def aupdate_account_sitelinks(
        self,
        account_id: str,
        updates: list[dict[str, Any]],
        *,
        customer_id: str | None = None,
    ) -> dict[str, Any]:
        """Update account sitelinks (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            updates=updates,
        )
        return await self._client._aput("/v1/ads/accounts/sitelinks", data=payload)

    async def aremove_account_sitelink(
        self, account_id: str, asset_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """Remove account sitelink (async)"""
        return await self._client._adelete("/v1/ads/accounts/sitelinks")

    async def alist_account_structured_snippets(
        self, account_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """List account snippets (async)"""
        params = self._build_params(
            account_id=account_id,
            customer_id=customer_id,
        )
        return await self._client._aget(
            "/v1/ads/accounts/structured-snippets", params=params
        )

    async def aadd_account_structured_snippets(
        self,
        account_id: str,
        structured_snippets: list[Any],
        *,
        customer_id: str | None = None,
    ) -> dict[str, Any]:
        """Add account snippets (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            structured_snippets=structured_snippets,
        )
        return await self._client._apost(
            "/v1/ads/accounts/structured-snippets", data=payload
        )

    async def aupdate_account_structured_snippets(
        self,
        account_id: str,
        updates: list[dict[str, Any]],
        *,
        customer_id: str | None = None,
    ) -> dict[str, Any]:
        """Update account snippets (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            updates=updates,
        )
        return await self._client._aput(
            "/v1/ads/accounts/structured-snippets", data=payload
        )

    async def aremove_account_structured_snippet(
        self, account_id: str, asset_id: str, *, customer_id: str | None = None
    ) -> dict[str, Any]:
        """Remove account snippet (async)"""
        return await self._client._adelete("/v1/ads/accounts/structured-snippets")

    async def aget_ad_account_finance(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """Ad account finances (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
        )
        return await self._client._aget("/v1/ads/accounts/finance", params=params)

    async def acreate_ad_account(
        self,
        account_id: str,
        business_id: str,
        name: str,
        currency: str,
        timezone_id: int,
        *,
        end_advertiser: str | None = "NONE",
        media_agency: str | None = "NONE",
        partner: str | None = "NONE",
        invoice: bool | None = None,
        invoice_group_id: str | None = None,
        invoicing_emails: list[str] | None = None,
        io: bool | None = None,
        po_number: str | None = None,
        funding_id: str | None = None,
        ad_account_created_from_bm_flag: bool | None = None,
    ) -> dict[str, Any]:
        """Create Meta ad account (async)"""
        payload = self._build_payload(
            account_id=account_id,
            business_id=business_id,
            name=name,
            currency=currency,
            timezone_id=timezone_id,
            end_advertiser=end_advertiser,
            media_agency=media_agency,
            partner=partner,
            invoice=invoice,
            invoice_group_id=invoice_group_id,
            invoicing_emails=invoicing_emails,
            io=io,
            po_number=po_number,
            funding_id=funding_id,
            ad_account_created_from_bm_flag=ad_account_created_from_bm_flag,
        )
        return await self._client._apost("/v1/ads/accounts", data=payload)

    async def alist_ad_accounts(
        self,
        account_id: str,
        *,
        ad_account_id: str | None = None,
        limit: int | None = None,
    ) -> dict[str, Any]:
        """List ad accounts (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            limit=limit,
        )
        return await self._client._aget("/v1/ads/accounts", params=params)

    async def aupdate_ad_account(
        self,
        account_id: str,
        ad_account_id: str,
        default_dsa_beneficiary: str,
        *,
        default_dsa_payor: str | None = None,
    ) -> dict[str, Any]:
        """Update ad account settings (async)"""
        payload = self._build_payload(
            account_id=account_id,
            ad_account_id=ad_account_id,
            default_dsa_beneficiary=default_dsa_beneficiary,
            default_dsa_payor=default_dsa_payor,
        )
        return await self._client._apatch("/v1/ads/accounts", data=payload)

    async def aget_dsa_defaults(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """Get ad account DSA defaults (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
        )
        return await self._client._aget("/v1/ads/dsa-defaults", params=params)

    async def aget_dsa_recommendations(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """Get DSA recommendations (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
        )
        return await self._client._aget("/v1/ads/dsa-recommendations", params=params)

    async def alist_custom_conversions(
        self, account_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """List custom conversions (async)"""
        params = self._build_params(
            ad_account_id=ad_account_id,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/custom-conversions", params=params
        )

    async def acreate_custom_conversion(
        self,
        account_id: str,
        ad_account_id: str,
        name: str,
        pixel_id: str,
        custom_event_type: str,
        rule: dict[str, Any],
    ) -> dict[str, Any]:
        """Create custom conversion (async)"""
        payload = self._build_payload(
            ad_account_id=ad_account_id,
            name=name,
            pixel_id=pixel_id,
            custom_event_type=custom_event_type,
            rule=rule,
        )
        return await self._client._apost(
            f"/v1/accounts/{account_id}/custom-conversions", data=payload
        )

    async def alist_tik_tok_ad_pixels(
        self,
        account_id: str,
        *,
        advertiser_id: str | None = None,
        code: str | None = None,
    ) -> dict[str, Any]:
        """List TikTok ad pixels (async)"""
        params = self._build_params(
            account_id=account_id,
            advertiser_id=advertiser_id,
            code=code,
        )
        return await self._client._aget("/v1/ads/pixels", params=params)
