"""
Auto-generated ad_insights resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class AdInsightsResource:
    """
    ad_insights operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.

        Enum members are unwrapped to their value: httpx serializes params
        via str(), which yields "ClassName.MEMBER" for Enum members, so
        e.g. ``status=PostStatus.FAILED`` would otherwise reach the API as
        ``status=PostStatus.FAILED`` instead of ``status=failed``.
        """
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None or v == "":
                continue
            result[to_camel(k)] = v
        return result

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values. Enum members are
        unwrapped to their value so JSON bodies carry e.g. "failed" rather
        than a raw Enum member (plain Enum members are not JSON-serializable).
        """
        from datetime import datetime
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def get_campaign_analytics(
        self,
        campaign_id: str,
        *,
        platform: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        breakdowns: str | None = None,
    ) -> dict[str, Any]:
        """Get campaign analytics"""
        params = self._build_params(
            platform=platform,
            from_date=from_date,
            to_date=to_date,
            breakdowns=breakdowns,
        )
        return self._client._get(
            f"/v1/ads/campaigns/{campaign_id}/analytics", params=params
        )

    def generate_keyword_ideas(
        self,
        account_id: str,
        *,
        customer_id: str | None = None,
        seed_keywords: list[str] | None = None,
        seed_url: str | None = None,
        countries: list[str] | None = None,
        language_constant_id: str | None = "1000",
        network: str | None = "GOOGLE_SEARCH",
        include_adult_keywords: bool | None = None,
        page_size: int | None = None,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """Generate keyword ideas (Google Keyword Planner)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            seed_keywords=seed_keywords,
            seed_url=seed_url,
            countries=countries,
            language_constant_id=language_constant_id,
            network=network,
            include_adult_keywords=include_adult_keywords,
            page_size=page_size,
            page_token=page_token,
        )
        return self._client._post("/v1/ads/keywords/ideas", data=payload)

    def generate_keyword_historical_metrics(
        self,
        account_id: str,
        keywords: list[str],
        *,
        customer_id: str | None = None,
        countries: list[str] | None = None,
        language_constant_id: str | None = "1000",
        network: str | None = "GOOGLE_SEARCH",
        include_adult_keywords: bool | None = None,
        include_average_cpc: bool | None = None,
    ) -> dict[str, Any]:
        """Historical keyword metrics (Google Keyword Planner)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            keywords=keywords,
            countries=countries,
            language_constant_id=language_constant_id,
            network=network,
            include_adult_keywords=include_adult_keywords,
            include_average_cpc=include_average_cpc,
        )
        return self._client._post("/v1/ads/keywords/historical-metrics", data=payload)

    def query_ad_insights(
        self,
        account_id: str,
        *,
        object_id: str | None = None,
        query: str | None = None,
        customer_id: str | None = None,
        page_token: str | None = None,
        level: str | None = None,
        fields: str | None = None,
        breakdowns: str | None = None,
        action_breakdowns: str | None = None,
        action_attribution_windows: str | None = None,
        action_report_time: str | None = None,
        use_unified_attribution_setting: bool | None = None,
        filtering: str | None = None,
        date_preset: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        time_increment: str | None = None,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Flexible live insights query"""
        params = self._build_params(
            account_id=account_id,
            object_id=object_id,
            query=query,
            customer_id=customer_id,
            page_token=page_token,
            level=level,
            fields=fields,
            breakdowns=breakdowns,
            action_breakdowns=action_breakdowns,
            action_attribution_windows=action_attribution_windows,
            action_report_time=action_report_time,
            use_unified_attribution_setting=use_unified_attribution_setting,
            filtering=filtering,
            date_preset=date_preset,
            from_date=from_date,
            to_date=to_date,
            time_increment=time_increment,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/ads/insights", params=params)

    def create_ad_insights_report(
        self,
        account_id: str,
        object_id: str,
        *,
        level: str | None = None,
        fields: str | None = None,
        breakdowns: str | None = None,
        action_breakdowns: str | None = None,
        action_attribution_windows: list[str] | None = None,
        action_report_time: str | None = None,
        use_unified_attribution_setting: bool | None = None,
        filtering: list[dict[str, Any]] | None = None,
        date_preset: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        time_increment: Any | None = None,
    ) -> dict[str, Any]:
        """Submit an async insights report run"""
        payload = self._build_payload(
            account_id=account_id,
            object_id=object_id,
            level=level,
            fields=fields,
            breakdowns=breakdowns,
            action_breakdowns=action_breakdowns,
            action_attribution_windows=action_attribution_windows,
            action_report_time=action_report_time,
            use_unified_attribution_setting=use_unified_attribution_setting,
            filtering=filtering,
            date_preset=date_preset,
            from_date=from_date,
            to_date=to_date,
            time_increment=time_increment,
        )
        return self._client._post("/v1/ads/insights/reports", data=payload)

    def get_ad_insights_report(
        self,
        report_run_id: str,
        account_id: str,
        *,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Poll an async insights report run"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            after=after,
        )
        return self._client._get(
            f"/v1/ads/insights/reports/{report_run_id}", params=params
        )

    def get_ad_analytics(
        self,
        ad_id: str,
        *,
        from_date: str | None = None,
        to_date: str | None = None,
        breakdowns: str | None = None,
    ) -> dict[str, Any]:
        """Get ad analytics"""
        params = self._build_params(
            from_date=from_date,
            to_date=to_date,
            breakdowns=breakdowns,
        )
        return self._client._get(f"/v1/ads/{ad_id}/analytics", params=params)

    async def aget_campaign_analytics(
        self,
        campaign_id: str,
        *,
        platform: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        breakdowns: str | None = None,
    ) -> dict[str, Any]:
        """Get campaign analytics (async)"""
        params = self._build_params(
            platform=platform,
            from_date=from_date,
            to_date=to_date,
            breakdowns=breakdowns,
        )
        return await self._client._aget(
            f"/v1/ads/campaigns/{campaign_id}/analytics", params=params
        )

    async def agenerate_keyword_ideas(
        self,
        account_id: str,
        *,
        customer_id: str | None = None,
        seed_keywords: list[str] | None = None,
        seed_url: str | None = None,
        countries: list[str] | None = None,
        language_constant_id: str | None = "1000",
        network: str | None = "GOOGLE_SEARCH",
        include_adult_keywords: bool | None = None,
        page_size: int | None = None,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """Generate keyword ideas (Google Keyword Planner) (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            seed_keywords=seed_keywords,
            seed_url=seed_url,
            countries=countries,
            language_constant_id=language_constant_id,
            network=network,
            include_adult_keywords=include_adult_keywords,
            page_size=page_size,
            page_token=page_token,
        )
        return await self._client._apost("/v1/ads/keywords/ideas", data=payload)

    async def agenerate_keyword_historical_metrics(
        self,
        account_id: str,
        keywords: list[str],
        *,
        customer_id: str | None = None,
        countries: list[str] | None = None,
        language_constant_id: str | None = "1000",
        network: str | None = "GOOGLE_SEARCH",
        include_adult_keywords: bool | None = None,
        include_average_cpc: bool | None = None,
    ) -> dict[str, Any]:
        """Historical keyword metrics (Google Keyword Planner) (async)"""
        payload = self._build_payload(
            account_id=account_id,
            customer_id=customer_id,
            keywords=keywords,
            countries=countries,
            language_constant_id=language_constant_id,
            network=network,
            include_adult_keywords=include_adult_keywords,
            include_average_cpc=include_average_cpc,
        )
        return await self._client._apost(
            "/v1/ads/keywords/historical-metrics", data=payload
        )

    async def aquery_ad_insights(
        self,
        account_id: str,
        *,
        object_id: str | None = None,
        query: str | None = None,
        customer_id: str | None = None,
        page_token: str | None = None,
        level: str | None = None,
        fields: str | None = None,
        breakdowns: str | None = None,
        action_breakdowns: str | None = None,
        action_attribution_windows: str | None = None,
        action_report_time: str | None = None,
        use_unified_attribution_setting: bool | None = None,
        filtering: str | None = None,
        date_preset: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        time_increment: str | None = None,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Flexible live insights query (async)"""
        params = self._build_params(
            account_id=account_id,
            object_id=object_id,
            query=query,
            customer_id=customer_id,
            page_token=page_token,
            level=level,
            fields=fields,
            breakdowns=breakdowns,
            action_breakdowns=action_breakdowns,
            action_attribution_windows=action_attribution_windows,
            action_report_time=action_report_time,
            use_unified_attribution_setting=use_unified_attribution_setting,
            filtering=filtering,
            date_preset=date_preset,
            from_date=from_date,
            to_date=to_date,
            time_increment=time_increment,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/ads/insights", params=params)

    async def acreate_ad_insights_report(
        self,
        account_id: str,
        object_id: str,
        *,
        level: str | None = None,
        fields: str | None = None,
        breakdowns: str | None = None,
        action_breakdowns: str | None = None,
        action_attribution_windows: list[str] | None = None,
        action_report_time: str | None = None,
        use_unified_attribution_setting: bool | None = None,
        filtering: list[dict[str, Any]] | None = None,
        date_preset: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        time_increment: Any | None = None,
    ) -> dict[str, Any]:
        """Submit an async insights report run (async)"""
        payload = self._build_payload(
            account_id=account_id,
            object_id=object_id,
            level=level,
            fields=fields,
            breakdowns=breakdowns,
            action_breakdowns=action_breakdowns,
            action_attribution_windows=action_attribution_windows,
            action_report_time=action_report_time,
            use_unified_attribution_setting=use_unified_attribution_setting,
            filtering=filtering,
            date_preset=date_preset,
            from_date=from_date,
            to_date=to_date,
            time_increment=time_increment,
        )
        return await self._client._apost("/v1/ads/insights/reports", data=payload)

    async def aget_ad_insights_report(
        self,
        report_run_id: str,
        account_id: str,
        *,
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Poll an async insights report run (async)"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            after=after,
        )
        return await self._client._aget(
            f"/v1/ads/insights/reports/{report_run_id}", params=params
        )

    async def aget_ad_analytics(
        self,
        ad_id: str,
        *,
        from_date: str | None = None,
        to_date: str | None = None,
        breakdowns: str | None = None,
    ) -> dict[str, Any]:
        """Get ad analytics (async)"""
        params = self._build_params(
            from_date=from_date,
            to_date=to_date,
            breakdowns=breakdowns,
        )
        return await self._client._aget(f"/v1/ads/{ad_id}/analytics", params=params)
