"""
Auto-generated ads resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from datetime import datetime

    from ..client.base import BaseClient


class AdsResource:
    """
    ads operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.
        """

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None and v != ""}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def list_ads(
        self,
        *,
        page: int | None = 1,
        limit: int | None = 50,
        source: str | None = "all",
        status: Any | None = None,
        platform: str | None = None,
        account_id: str | None = None,
        ad_account_id: str | None = None,
        profile_id: str | None = None,
        campaign_id: str | None = None,
        platform_ad_id: str | None = None,
        effective_object_story_id: str | None = None,
        effective_instagram_media_id: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
    ) -> dict[str, Any]:
        """List ads"""
        params = self._build_params(
            page=page,
            limit=limit,
            source=source,
            status=status,
            platform=platform,
            account_id=account_id,
            ad_account_id=ad_account_id,
            profile_id=profile_id,
            campaign_id=campaign_id,
            platform_ad_id=platform_ad_id,
            effective_object_story_id=effective_object_story_id,
            effective_instagram_media_id=effective_instagram_media_id,
            from_date=from_date,
            to_date=to_date,
        )
        return self._client._get("/v1/ads", params=params)

    def get_ad(self, ad_id: str) -> dict[str, Any]:
        """Get ad details"""
        return self._client._get(f"/v1/ads/{ad_id}")

    def update_ad(
        self,
        ad_id: str,
        *,
        status: str | None = None,
        budget: dict[str, Any] | None = None,
        targeting: dict[str, Any] | None = None,
        creative: dict[str, Any] | None = None,
        name: str | None = None,
    ) -> dict[str, Any]:
        """Update ad"""
        payload = self._build_payload(
            status=status,
            budget=budget,
            targeting=targeting,
            creative=creative,
            name=name,
        )
        return self._client._put(f"/v1/ads/{ad_id}", data=payload)

    def delete_ad(self, ad_id: str) -> dict[str, Any]:
        """Cancel an ad"""
        return self._client._delete(f"/v1/ads/{ad_id}")

    def get_ad_analytics(
        self,
        ad_id: str,
        *,
        from_date: str | None = None,
        to_date: str | None = None,
        breakdowns: str | None = None,
    ) -> dict[str, Any]:
        """Get ad analytics"""
        params = self._build_params(
            from_date=from_date,
            to_date=to_date,
            breakdowns=breakdowns,
        )
        return self._client._get(f"/v1/ads/{ad_id}/analytics", params=params)

    def get_ad_comments(
        self,
        ad_id: str,
        *,
        placement: str | None = None,
        limit: int | None = 25,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """List comments on an ad"""
        params = self._build_params(
            placement=placement,
            limit=limit,
            cursor=cursor,
        )
        return self._client._get(f"/v1/ads/{ad_id}/comments", params=params)

    def list_ads_business_centers(self, account_id: str) -> dict[str, Any]:
        """List TikTok Business Centers"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get("/v1/ads/business-centers", params=params)

    def list_ad_accounts(
        self,
        account_id: str,
        *,
        ad_account_id: str | None = None,
        limit: int | None = None,
    ) -> dict[str, Any]:
        """List ad accounts"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            limit=limit,
        )
        return self._client._get("/v1/ads/accounts", params=params)

    def boost_post(
        self,
        account_id: str,
        ad_account_id: str,
        name: str,
        goal: str,
        budget: dict[str, Any],
        *,
        post_id: str | None = None,
        platform_post_id: str | None = None,
        currency: str | None = None,
        schedule: dict[str, Any] | None = None,
        targeting: dict[str, Any] | None = None,
        bid_strategy: Any | None = None,
        bid_amount: float | None = None,
        roas_average_floor: float | None = None,
        tracking: dict[str, Any] | None = None,
        special_ad_categories: list[str] | None = None,
        link_url: str | None = None,
        call_to_action: str | None = None,
        spark_auth_code: str | None = None,
        dsa_beneficiary: str | None = None,
        dsa_payor: str | None = None,
    ) -> dict[str, Any]:
        """Boost post as ad"""
        payload = self._build_payload(
            post_id=post_id,
            platform_post_id=platform_post_id,
            account_id=account_id,
            ad_account_id=ad_account_id,
            name=name,
            goal=goal,
            budget=budget,
            currency=currency,
            schedule=schedule,
            targeting=targeting,
            bid_strategy=bid_strategy,
            bid_amount=bid_amount,
            roas_average_floor=roas_average_floor,
            tracking=tracking,
            special_ad_categories=special_ad_categories,
            link_url=link_url,
            call_to_action=call_to_action,
            spark_auth_code=spark_auth_code,
            dsa_beneficiary=dsa_beneficiary,
            dsa_payor=dsa_payor,
        )
        return self._client._post("/v1/ads/boost", data=payload)

    def create_standalone_ad(
        self,
        account_id: str,
        ad_account_id: str,
        name: str,
        *,
        goal: str | None = None,
        budget_amount: float | None = None,
        budget_type: str | None = None,
        currency: str | None = None,
        headline: str | None = None,
        long_headline: str | None = None,
        body: str | None = None,
        call_to_action: str | None = None,
        link_url: str | None = None,
        image_url: str | None = None,
        images: dict[str, Any] | None = None,
        video: dict[str, Any] | None = None,
        creatives: list[dict[str, Any]] | None = None,
        ad_set_id: str | None = None,
        business_name: str | None = None,
        board_id: str | None = None,
        countries: list[str] | None = None,
        cities: list[dict[str, Any]] | None = None,
        regions: list[dict[str, Any]] | None = None,
        age_min: int | None = None,
        age_max: int | None = None,
        interests: list[dict[str, Any]] | None = None,
        end_date: datetime | str | None = None,
        audience_id: str | None = None,
        campaign_type: str | None = "display",
        keywords: list[str] | None = None,
        additional_headlines: list[str] | None = None,
        additional_descriptions: list[str] | None = None,
        advantage_audience: int | None = None,
        gender: str | None = "all",
        bid_strategy: Any | None = None,
        bid_amount: float | None = None,
        roas_average_floor: float | None = None,
        dsa_beneficiary: str | None = None,
        dsa_payor: str | None = None,
        brand_identity: dict[str, Any] | None = None,
        identity_type: str | None = None,
        promoted_object: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Create standalone ad"""
        payload = self._build_payload(
            account_id=account_id,
            ad_account_id=ad_account_id,
            name=name,
            goal=goal,
            budget_amount=budget_amount,
            budget_type=budget_type,
            currency=currency,
            headline=headline,
            long_headline=long_headline,
            body=body,
            call_to_action=call_to_action,
            link_url=link_url,
            image_url=image_url,
            images=images,
            video=video,
            creatives=creatives,
            ad_set_id=ad_set_id,
            business_name=business_name,
            board_id=board_id,
            countries=countries,
            cities=cities,
            regions=regions,
            age_min=age_min,
            age_max=age_max,
            interests=interests,
            end_date=end_date,
            audience_id=audience_id,
            campaign_type=campaign_type,
            keywords=keywords,
            additional_headlines=additional_headlines,
            additional_descriptions=additional_descriptions,
            advantage_audience=advantage_audience,
            gender=gender,
            bid_strategy=bid_strategy,
            bid_amount=bid_amount,
            roas_average_floor=roas_average_floor,
            dsa_beneficiary=dsa_beneficiary,
            dsa_payor=dsa_payor,
            brand_identity=brand_identity,
            identity_type=identity_type,
            promoted_object=promoted_object,
        )
        return self._client._post("/v1/ads/create", data=payload)

    def search_ad_interests(self, q: str, account_id: str) -> dict[str, Any]:
        """Search targeting interests"""
        params = self._build_params(
            q=q,
            account_id=account_id,
        )
        return self._client._get("/v1/ads/interests", params=params)

    def search_ad_targeting_locations(
        self,
        account_id: str,
        q: str,
        *,
        type: str | None = "city",
        country_code: str | None = None,
        limit: int | None = 25,
    ) -> dict[str, Any]:
        """Search geo targeting locations (Meta)"""
        params = self._build_params(
            account_id=account_id,
            q=q,
            type=type,
            country_code=country_code,
            limit=limit,
        )
        return self._client._get("/v1/ads/targeting/search", params=params)

    def send_conversions(
        self,
        account_id: str,
        destination_id: str,
        events: list[Any],
        *,
        test_code: str | None = None,
        consent: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Send conversion events to an ad platform"""
        payload = self._build_payload(
            account_id=account_id,
            destination_id=destination_id,
            events=events,
            test_code=test_code,
            consent=consent,
        )
        return self._client._post("/v1/ads/conversions", data=payload)

    def list_conversion_destinations(self, account_id: str) -> dict[str, Any]:
        """List destinations for the Conversions API"""
        return self._client._get(f"/v1/accounts/{account_id}/conversion-destinations")

    def create_conversion_destination(
        self,
        account_id: str,
        ad_account_id: str,
        name: str,
        type: str,
        *,
        attribution_type: str | None = None,
        post_click_attribution_window_size: int | None = None,
        view_through_attribution_window_size: int | None = None,
        value_type: str | None = None,
        value: dict[str, Any] | None = None,
        auto_association_type: str | None = "ALL_CAMPAIGNS",
    ) -> dict[str, Any]:
        """Create a conversion destination (LinkedIn)"""
        payload = self._build_payload(
            ad_account_id=ad_account_id,
            name=name,
            type=type,
            attribution_type=attribution_type,
            post_click_attribution_window_size=post_click_attribution_window_size,
            view_through_attribution_window_size=view_through_attribution_window_size,
            value_type=value_type,
            value=value,
            auto_association_type=auto_association_type,
        )
        return self._client._post(
            f"/v1/accounts/{account_id}/conversion-destinations", data=payload
        )

    def get_conversion_destination(
        self, account_id: str, destination_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """Fetch a single conversion destination"""
        params = self._build_params(
            ad_account_id=ad_account_id,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}",
            params=params,
        )

    def update_conversion_destination(
        self,
        account_id: str,
        destination_id: str,
        ad_account_id: str,
        *,
        name: str | None = None,
        enabled: bool | None = None,
        attribution_type: str | None = None,
        post_click_attribution_window_size: int | None = None,
        view_through_attribution_window_size: int | None = None,
        value_type: str | None = None,
        value: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Update a conversion destination"""
        payload = self._build_payload(
            ad_account_id=ad_account_id,
            name=name,
            enabled=enabled,
            attribution_type=attribution_type,
            post_click_attribution_window_size=post_click_attribution_window_size,
            view_through_attribution_window_size=view_through_attribution_window_size,
            value_type=value_type,
            value=value,
        )
        return self._client._patch(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}",
            data=payload,
        )

    def delete_conversion_destination(
        self, account_id: str, destination_id: str, *, ad_account_id: str | None = None
    ) -> dict[str, Any]:
        """Soft-delete a conversion destination"""
        params = self._build_params(
            ad_account_id=ad_account_id,
        )
        return self._client._delete(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}",
            params=params,
        )

    def list_conversion_associations(
        self, account_id: str, destination_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """List campaigns associated with a conversion destination"""
        params = self._build_params(
            ad_account_id=ad_account_id,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}/associations",
            params=params,
        )

    def add_conversion_associations(
        self,
        account_id: str,
        destination_id: str,
        ad_account_id: str,
        campaign_ids: list[str],
    ) -> dict[str, Any]:
        """Associate campaigns with a conversion destination"""
        payload = self._build_payload(
            ad_account_id=ad_account_id,
            campaign_ids=campaign_ids,
        )
        return self._client._post(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}/associations",
            data=payload,
        )

    def remove_conversion_associations(
        self,
        account_id: str,
        destination_id: str,
        ad_account_id: str,
        campaign_ids: str,
    ) -> dict[str, Any]:
        """Remove campaign↔conversion associations"""
        params = self._build_params(
            ad_account_id=ad_account_id,
            campaign_ids=campaign_ids,
        )
        return self._client._delete(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}/associations",
            params=params,
        )

    def get_conversion_metrics(
        self,
        account_id: str,
        destination_id: str,
        ad_account_id: str,
        start_date: str,
        *,
        end_date: str | None = None,
        granularity: str | None = "DAILY",
    ) -> dict[str, Any]:
        """Fetch attribution metrics for a conversion destination"""
        params = self._build_params(
            ad_account_id=ad_account_id,
            start_date=start_date,
            end_date=end_date,
            granularity=granularity,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}/metrics",
            params=params,
        )

    def create_ctwa_ad(
        self,
        account_id: str,
        ad_account_id: str,
        name: str,
        headline: str,
        body: str,
        budget_amount: float,
        budget_type: str,
        *,
        image_url: str | None = None,
        video: dict[str, Any] | None = None,
        currency: str | None = None,
        end_date: datetime | str | None = None,
        countries: list[str] | None = None,
        age_min: int | None = None,
        age_max: int | None = None,
        interests: list[dict[str, Any]] | None = None,
        audience_id: str | None = None,
        advantage_audience: int | None = None,
        objective: str | None = None,
        dsa_beneficiary: str | None = None,
        dsa_payor: str | None = None,
    ) -> dict[str, Any]:
        """Create Click-to-WhatsApp ad"""
        payload = self._build_payload(
            account_id=account_id,
            ad_account_id=ad_account_id,
            name=name,
            headline=headline,
            body=body,
            image_url=image_url,
            video=video,
            budget_amount=budget_amount,
            budget_type=budget_type,
            currency=currency,
            end_date=end_date,
            countries=countries,
            age_min=age_min,
            age_max=age_max,
            interests=interests,
            audience_id=audience_id,
            advantage_audience=advantage_audience,
            objective=objective,
            dsa_beneficiary=dsa_beneficiary,
            dsa_payor=dsa_payor,
        )
        return self._client._post("/v1/ads/ctwa", data=payload)

    async def alist_ads(
        self,
        *,
        page: int | None = 1,
        limit: int | None = 50,
        source: str | None = "all",
        status: Any | None = None,
        platform: str | None = None,
        account_id: str | None = None,
        ad_account_id: str | None = None,
        profile_id: str | None = None,
        campaign_id: str | None = None,
        platform_ad_id: str | None = None,
        effective_object_story_id: str | None = None,
        effective_instagram_media_id: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
    ) -> dict[str, Any]:
        """List ads (async)"""
        params = self._build_params(
            page=page,
            limit=limit,
            source=source,
            status=status,
            platform=platform,
            account_id=account_id,
            ad_account_id=ad_account_id,
            profile_id=profile_id,
            campaign_id=campaign_id,
            platform_ad_id=platform_ad_id,
            effective_object_story_id=effective_object_story_id,
            effective_instagram_media_id=effective_instagram_media_id,
            from_date=from_date,
            to_date=to_date,
        )
        return await self._client._aget("/v1/ads", params=params)

    async def aget_ad(self, ad_id: str) -> dict[str, Any]:
        """Get ad details (async)"""
        return await self._client._aget(f"/v1/ads/{ad_id}")

    async def aupdate_ad(
        self,
        ad_id: str,
        *,
        status: str | None = None,
        budget: dict[str, Any] | None = None,
        targeting: dict[str, Any] | None = None,
        creative: dict[str, Any] | None = None,
        name: str | None = None,
    ) -> dict[str, Any]:
        """Update ad (async)"""
        payload = self._build_payload(
            status=status,
            budget=budget,
            targeting=targeting,
            creative=creative,
            name=name,
        )
        return await self._client._aput(f"/v1/ads/{ad_id}", data=payload)

    async def adelete_ad(self, ad_id: str) -> dict[str, Any]:
        """Cancel an ad (async)"""
        return await self._client._adelete(f"/v1/ads/{ad_id}")

    async def aget_ad_analytics(
        self,
        ad_id: str,
        *,
        from_date: str | None = None,
        to_date: str | None = None,
        breakdowns: str | None = None,
    ) -> dict[str, Any]:
        """Get ad analytics (async)"""
        params = self._build_params(
            from_date=from_date,
            to_date=to_date,
            breakdowns=breakdowns,
        )
        return await self._client._aget(f"/v1/ads/{ad_id}/analytics", params=params)

    async def aget_ad_comments(
        self,
        ad_id: str,
        *,
        placement: str | None = None,
        limit: int | None = 25,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """List comments on an ad (async)"""
        params = self._build_params(
            placement=placement,
            limit=limit,
            cursor=cursor,
        )
        return await self._client._aget(f"/v1/ads/{ad_id}/comments", params=params)

    async def alist_ads_business_centers(self, account_id: str) -> dict[str, Any]:
        """List TikTok Business Centers (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget("/v1/ads/business-centers", params=params)

    async def alist_ad_accounts(
        self,
        account_id: str,
        *,
        ad_account_id: str | None = None,
        limit: int | None = None,
    ) -> dict[str, Any]:
        """List ad accounts (async)"""
        params = self._build_params(
            account_id=account_id,
            ad_account_id=ad_account_id,
            limit=limit,
        )
        return await self._client._aget("/v1/ads/accounts", params=params)

    async def aboost_post(
        self,
        account_id: str,
        ad_account_id: str,
        name: str,
        goal: str,
        budget: dict[str, Any],
        *,
        post_id: str | None = None,
        platform_post_id: str | None = None,
        currency: str | None = None,
        schedule: dict[str, Any] | None = None,
        targeting: dict[str, Any] | None = None,
        bid_strategy: Any | None = None,
        bid_amount: float | None = None,
        roas_average_floor: float | None = None,
        tracking: dict[str, Any] | None = None,
        special_ad_categories: list[str] | None = None,
        link_url: str | None = None,
        call_to_action: str | None = None,
        spark_auth_code: str | None = None,
        dsa_beneficiary: str | None = None,
        dsa_payor: str | None = None,
    ) -> dict[str, Any]:
        """Boost post as ad (async)"""
        payload = self._build_payload(
            post_id=post_id,
            platform_post_id=platform_post_id,
            account_id=account_id,
            ad_account_id=ad_account_id,
            name=name,
            goal=goal,
            budget=budget,
            currency=currency,
            schedule=schedule,
            targeting=targeting,
            bid_strategy=bid_strategy,
            bid_amount=bid_amount,
            roas_average_floor=roas_average_floor,
            tracking=tracking,
            special_ad_categories=special_ad_categories,
            link_url=link_url,
            call_to_action=call_to_action,
            spark_auth_code=spark_auth_code,
            dsa_beneficiary=dsa_beneficiary,
            dsa_payor=dsa_payor,
        )
        return await self._client._apost("/v1/ads/boost", data=payload)

    async def acreate_standalone_ad(
        self,
        account_id: str,
        ad_account_id: str,
        name: str,
        *,
        goal: str | None = None,
        budget_amount: float | None = None,
        budget_type: str | None = None,
        currency: str | None = None,
        headline: str | None = None,
        long_headline: str | None = None,
        body: str | None = None,
        call_to_action: str | None = None,
        link_url: str | None = None,
        image_url: str | None = None,
        images: dict[str, Any] | None = None,
        video: dict[str, Any] | None = None,
        creatives: list[dict[str, Any]] | None = None,
        ad_set_id: str | None = None,
        business_name: str | None = None,
        board_id: str | None = None,
        countries: list[str] | None = None,
        cities: list[dict[str, Any]] | None = None,
        regions: list[dict[str, Any]] | None = None,
        age_min: int | None = None,
        age_max: int | None = None,
        interests: list[dict[str, Any]] | None = None,
        end_date: datetime | str | None = None,
        audience_id: str | None = None,
        campaign_type: str | None = "display",
        keywords: list[str] | None = None,
        additional_headlines: list[str] | None = None,
        additional_descriptions: list[str] | None = None,
        advantage_audience: int | None = None,
        gender: str | None = "all",
        bid_strategy: Any | None = None,
        bid_amount: float | None = None,
        roas_average_floor: float | None = None,
        dsa_beneficiary: str | None = None,
        dsa_payor: str | None = None,
        brand_identity: dict[str, Any] | None = None,
        identity_type: str | None = None,
        promoted_object: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Create standalone ad (async)"""
        payload = self._build_payload(
            account_id=account_id,
            ad_account_id=ad_account_id,
            name=name,
            goal=goal,
            budget_amount=budget_amount,
            budget_type=budget_type,
            currency=currency,
            headline=headline,
            long_headline=long_headline,
            body=body,
            call_to_action=call_to_action,
            link_url=link_url,
            image_url=image_url,
            images=images,
            video=video,
            creatives=creatives,
            ad_set_id=ad_set_id,
            business_name=business_name,
            board_id=board_id,
            countries=countries,
            cities=cities,
            regions=regions,
            age_min=age_min,
            age_max=age_max,
            interests=interests,
            end_date=end_date,
            audience_id=audience_id,
            campaign_type=campaign_type,
            keywords=keywords,
            additional_headlines=additional_headlines,
            additional_descriptions=additional_descriptions,
            advantage_audience=advantage_audience,
            gender=gender,
            bid_strategy=bid_strategy,
            bid_amount=bid_amount,
            roas_average_floor=roas_average_floor,
            dsa_beneficiary=dsa_beneficiary,
            dsa_payor=dsa_payor,
            brand_identity=brand_identity,
            identity_type=identity_type,
            promoted_object=promoted_object,
        )
        return await self._client._apost("/v1/ads/create", data=payload)

    async def asearch_ad_interests(self, q: str, account_id: str) -> dict[str, Any]:
        """Search targeting interests (async)"""
        params = self._build_params(
            q=q,
            account_id=account_id,
        )
        return await self._client._aget("/v1/ads/interests", params=params)

    async def asearch_ad_targeting_locations(
        self,
        account_id: str,
        q: str,
        *,
        type: str | None = "city",
        country_code: str | None = None,
        limit: int | None = 25,
    ) -> dict[str, Any]:
        """Search geo targeting locations (Meta) (async)"""
        params = self._build_params(
            account_id=account_id,
            q=q,
            type=type,
            country_code=country_code,
            limit=limit,
        )
        return await self._client._aget("/v1/ads/targeting/search", params=params)

    async def asend_conversions(
        self,
        account_id: str,
        destination_id: str,
        events: list[Any],
        *,
        test_code: str | None = None,
        consent: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Send conversion events to an ad platform (async)"""
        payload = self._build_payload(
            account_id=account_id,
            destination_id=destination_id,
            events=events,
            test_code=test_code,
            consent=consent,
        )
        return await self._client._apost("/v1/ads/conversions", data=payload)

    async def alist_conversion_destinations(self, account_id: str) -> dict[str, Any]:
        """List destinations for the Conversions API (async)"""
        return await self._client._aget(
            f"/v1/accounts/{account_id}/conversion-destinations"
        )

    async def acreate_conversion_destination(
        self,
        account_id: str,
        ad_account_id: str,
        name: str,
        type: str,
        *,
        attribution_type: str | None = None,
        post_click_attribution_window_size: int | None = None,
        view_through_attribution_window_size: int | None = None,
        value_type: str | None = None,
        value: dict[str, Any] | None = None,
        auto_association_type: str | None = "ALL_CAMPAIGNS",
    ) -> dict[str, Any]:
        """Create a conversion destination (LinkedIn) (async)"""
        payload = self._build_payload(
            ad_account_id=ad_account_id,
            name=name,
            type=type,
            attribution_type=attribution_type,
            post_click_attribution_window_size=post_click_attribution_window_size,
            view_through_attribution_window_size=view_through_attribution_window_size,
            value_type=value_type,
            value=value,
            auto_association_type=auto_association_type,
        )
        return await self._client._apost(
            f"/v1/accounts/{account_id}/conversion-destinations", data=payload
        )

    async def aget_conversion_destination(
        self, account_id: str, destination_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """Fetch a single conversion destination (async)"""
        params = self._build_params(
            ad_account_id=ad_account_id,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}",
            params=params,
        )

    async def aupdate_conversion_destination(
        self,
        account_id: str,
        destination_id: str,
        ad_account_id: str,
        *,
        name: str | None = None,
        enabled: bool | None = None,
        attribution_type: str | None = None,
        post_click_attribution_window_size: int | None = None,
        view_through_attribution_window_size: int | None = None,
        value_type: str | None = None,
        value: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Update a conversion destination (async)"""
        payload = self._build_payload(
            ad_account_id=ad_account_id,
            name=name,
            enabled=enabled,
            attribution_type=attribution_type,
            post_click_attribution_window_size=post_click_attribution_window_size,
            view_through_attribution_window_size=view_through_attribution_window_size,
            value_type=value_type,
            value=value,
        )
        return await self._client._apatch(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}",
            data=payload,
        )

    async def adelete_conversion_destination(
        self, account_id: str, destination_id: str, *, ad_account_id: str | None = None
    ) -> dict[str, Any]:
        """Soft-delete a conversion destination (async)"""
        params = self._build_params(
            ad_account_id=ad_account_id,
        )
        return await self._client._adelete(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}",
            params=params,
        )

    async def alist_conversion_associations(
        self, account_id: str, destination_id: str, ad_account_id: str
    ) -> dict[str, Any]:
        """List campaigns associated with a conversion destination (async)"""
        params = self._build_params(
            ad_account_id=ad_account_id,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}/associations",
            params=params,
        )

    async def aadd_conversion_associations(
        self,
        account_id: str,
        destination_id: str,
        ad_account_id: str,
        campaign_ids: list[str],
    ) -> dict[str, Any]:
        """Associate campaigns with a conversion destination (async)"""
        payload = self._build_payload(
            ad_account_id=ad_account_id,
            campaign_ids=campaign_ids,
        )
        return await self._client._apost(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}/associations",
            data=payload,
        )

    async def aremove_conversion_associations(
        self,
        account_id: str,
        destination_id: str,
        ad_account_id: str,
        campaign_ids: str,
    ) -> dict[str, Any]:
        """Remove campaign↔conversion associations (async)"""
        params = self._build_params(
            ad_account_id=ad_account_id,
            campaign_ids=campaign_ids,
        )
        return await self._client._adelete(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}/associations",
            params=params,
        )

    async def aget_conversion_metrics(
        self,
        account_id: str,
        destination_id: str,
        ad_account_id: str,
        start_date: str,
        *,
        end_date: str | None = None,
        granularity: str | None = "DAILY",
    ) -> dict[str, Any]:
        """Fetch attribution metrics for a conversion destination (async)"""
        params = self._build_params(
            ad_account_id=ad_account_id,
            start_date=start_date,
            end_date=end_date,
            granularity=granularity,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/conversion-destinations/{destination_id}/metrics",
            params=params,
        )

    async def acreate_ctwa_ad(
        self,
        account_id: str,
        ad_account_id: str,
        name: str,
        headline: str,
        body: str,
        budget_amount: float,
        budget_type: str,
        *,
        image_url: str | None = None,
        video: dict[str, Any] | None = None,
        currency: str | None = None,
        end_date: datetime | str | None = None,
        countries: list[str] | None = None,
        age_min: int | None = None,
        age_max: int | None = None,
        interests: list[dict[str, Any]] | None = None,
        audience_id: str | None = None,
        advantage_audience: int | None = None,
        objective: str | None = None,
        dsa_beneficiary: str | None = None,
        dsa_payor: str | None = None,
    ) -> dict[str, Any]:
        """Create Click-to-WhatsApp ad (async)"""
        payload = self._build_payload(
            account_id=account_id,
            ad_account_id=ad_account_id,
            name=name,
            headline=headline,
            body=body,
            image_url=image_url,
            video=video,
            budget_amount=budget_amount,
            budget_type=budget_type,
            currency=currency,
            end_date=end_date,
            countries=countries,
            age_min=age_min,
            age_max=age_max,
            interests=interests,
            audience_id=audience_id,
            advantage_audience=advantage_audience,
            objective=objective,
            dsa_beneficiary=dsa_beneficiary,
            dsa_payor=dsa_payor,
        )
        return await self._client._apost("/v1/ads/ctwa", data=payload)
