"""
Auto-generated connected_apps resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class ConnectedAppsResource:
    """
    connected_apps operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.
        """

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None and v != ""}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def list_connected_apps(self) -> dict[str, Any]:
        """List connected apps"""
        return self._client._get("/v1/me/connected-apps")

    def revoke_connected_app(self, client_id: str) -> dict[str, Any]:
        """Revoke connected app"""
        return self._client._delete(f"/v1/me/connected-apps/{client_id}")

    async def alist_connected_apps(self) -> dict[str, Any]:
        """List connected apps (async)"""
        return await self._client._aget("/v1/me/connected-apps")

    async def arevoke_connected_app(self, client_id: str) -> dict[str, Any]:
        """Revoke connected app (async)"""
        return await self._client._adelete(f"/v1/me/connected-apps/{client_id}")
