"""
Auto-generated gmb_services resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class GmbServicesResource:
    """
    gmb_services operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.

        Enum members are unwrapped to their value: httpx serializes params
        via str(), which yields "ClassName.MEMBER" for Enum members, so
        e.g. ``status=PostStatus.FAILED`` would otherwise reach the API as
        ``status=PostStatus.FAILED`` instead of ``status=failed``.
        """
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None or v == "":
                continue
            result[to_camel(k)] = v
        return result

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values. Enum members are
        unwrapped to their value so JSON bodies carry e.g. "failed" rather
        than a raw Enum member (plain Enum members are not JSON-serializable).
        """
        from datetime import datetime
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def get_google_business_services(
        self, account_id: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Get services"""
        params = self._build_params(
            location_id=location_id,
        )
        return self._client._get(
            f"/v1/accounts/{account_id}/gmb-services", params=params
        )

    def update_google_business_services(
        self,
        account_id: str,
        service_items: list[dict[str, Any]],
        *,
        location_id: str | None = None,
    ) -> dict[str, Any]:
        """Replace services"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            service_items=service_items,
        )
        return self._client._put(
            f"/v1/accounts/{account_id}/gmb-services", data=payload, params=params
        )

    async def aget_google_business_services(
        self, account_id: str, *, location_id: str | None = None
    ) -> dict[str, Any]:
        """Get services (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        return await self._client._aget(
            f"/v1/accounts/{account_id}/gmb-services", params=params
        )

    async def aupdate_google_business_services(
        self,
        account_id: str,
        service_items: list[dict[str, Any]],
        *,
        location_id: str | None = None,
    ) -> dict[str, Any]:
        """Replace services (async)"""
        params = self._build_params(
            location_id=location_id,
        )
        payload = self._build_payload(
            service_items=service_items,
        )
        return await self._client._aput(
            f"/v1/accounts/{account_id}/gmb-services", data=payload, params=params
        )
