"""
Auto-generated invites resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class InvitesResource:
    """
    Team invitations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None values."""

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def create_invite_token(
        self, scope: str, *, profile_ids: list[str] | None = None
    ) -> dict[str, Any]:
        """Create a team member invite token"""
        payload = self._build_payload(
            scope=scope,
            profile_ids=profile_ids,
        )
        return self._client._post("/v1/invite/tokens", data=payload)

    def list_platform_invites(self, *, profile_id: str | None = None) -> dict[str, Any]:
        """List platform connection invites"""
        params = self._build_params(
            profile_id=profile_id,
        )
        return self._client._get("/v1/platform-invites", params=params)

    def create_platform_invite(self, profile_id: str, platform: str) -> dict[str, Any]:
        """Create a platform connection invite"""
        payload = self._build_payload(
            profile_id=profile_id,
            platform=platform,
        )
        return self._client._post("/v1/platform-invites", data=payload)

    def delete_platform_invite(self, id: str) -> dict[str, Any]:
        """Revoke a platform connection invite"""
        params = self._build_params(
            id=id,
        )
        return self._client._delete("/v1/platform-invites", params=params)

    async def acreate_invite_token(
        self, scope: str, *, profile_ids: list[str] | None = None
    ) -> dict[str, Any]:
        """Create a team member invite token (async)"""
        payload = self._build_payload(
            scope=scope,
            profile_ids=profile_ids,
        )
        return await self._client._apost("/v1/invite/tokens", data=payload)

    async def alist_platform_invites(
        self, *, profile_id: str | None = None
    ) -> dict[str, Any]:
        """List platform connection invites (async)"""
        params = self._build_params(
            profile_id=profile_id,
        )
        return await self._client._aget("/v1/platform-invites", params=params)

    async def acreate_platform_invite(
        self, profile_id: str, platform: str
    ) -> dict[str, Any]:
        """Create a platform connection invite (async)"""
        payload = self._build_payload(
            profile_id=profile_id,
            platform=platform,
        )
        return await self._client._apost("/v1/platform-invites", data=payload)

    async def adelete_platform_invite(self, id: str) -> dict[str, Any]:
        """Revoke a platform connection invite (async)"""
        params = self._build_params(
            id=id,
        )
        return await self._client._adelete("/v1/platform-invites", params=params)
