"""
Auto-generated lead_gen resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class LeadGenResource:
    """
    lead_gen operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.
        """

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None and v != ""}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def list_leads(
        self,
        *,
        form_id: str | None = None,
        account_id: str | None = None,
        limit: int | None = 25,
        since: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """List submitted leads"""
        params = self._build_params(
            form_id=form_id,
            account_id=account_id,
            limit=limit,
            since=since,
            cursor=cursor,
        )
        return self._client._get("/v1/ads/leads", params=params)

    def list_lead_forms(
        self, account_id: str, *, limit: int | None = 25, cursor: str | None = None
    ) -> dict[str, Any]:
        """List lead forms"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
        )
        return self._client._get("/v1/ads/lead-forms", params=params)

    def create_lead_form(
        self,
        account_id: str,
        name: str,
        questions: list[dict[str, Any]],
        privacy_policy_url: str,
        *,
        privacy_policy_link_text: str | None = None,
        follow_up_action_url: str | None = None,
        locale: str | None = None,
        thank_you_title: str | None = None,
        thank_you_body: str | None = None,
        thank_you_button_text: str | None = None,
        thank_you_button_type: str | None = None,
        thank_you_website_url: str | None = None,
        is_optimized_for_quality: bool | None = None,
    ) -> dict[str, Any]:
        """Create a lead form"""
        payload = self._build_payload(
            account_id=account_id,
            name=name,
            questions=questions,
            privacy_policy_url=privacy_policy_url,
            privacy_policy_link_text=privacy_policy_link_text,
            follow_up_action_url=follow_up_action_url,
            locale=locale,
            thank_you_title=thank_you_title,
            thank_you_body=thank_you_body,
            thank_you_button_text=thank_you_button_text,
            thank_you_button_type=thank_you_button_type,
            thank_you_website_url=thank_you_website_url,
            is_optimized_for_quality=is_optimized_for_quality,
        )
        return self._client._post("/v1/ads/lead-forms", data=payload)

    def get_lead_form(self, form_id: str, account_id: str) -> dict[str, Any]:
        """Get a lead form"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get(f"/v1/ads/lead-forms/{form_id}", params=params)

    def archive_lead_form(self, form_id: str, account_id: str) -> dict[str, Any]:
        """Archive a lead form"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._delete(f"/v1/ads/lead-forms/{form_id}", params=params)

    def list_form_leads(
        self,
        form_id: str,
        account_id: str,
        *,
        limit: int | None = 25,
        cursor: str | None = None,
        since: int | None = None,
    ) -> dict[str, Any]:
        """List leads for a single form"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
            since=since,
        )
        return self._client._get(f"/v1/ads/lead-forms/{form_id}/leads", params=params)

    def create_test_lead(
        self, form_id: str, account_id: str, field_data: list[dict[str, Any]]
    ) -> dict[str, Any]:
        """Create a test lead"""
        payload = self._build_payload(
            account_id=account_id,
            field_data=field_data,
        )
        return self._client._post(
            f"/v1/ads/lead-forms/{form_id}/test-leads", data=payload
        )

    async def alist_leads(
        self,
        *,
        form_id: str | None = None,
        account_id: str | None = None,
        limit: int | None = 25,
        since: int | None = None,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """List submitted leads (async)"""
        params = self._build_params(
            form_id=form_id,
            account_id=account_id,
            limit=limit,
            since=since,
            cursor=cursor,
        )
        return await self._client._aget("/v1/ads/leads", params=params)

    async def alist_lead_forms(
        self, account_id: str, *, limit: int | None = 25, cursor: str | None = None
    ) -> dict[str, Any]:
        """List lead forms (async)"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
        )
        return await self._client._aget("/v1/ads/lead-forms", params=params)

    async def acreate_lead_form(
        self,
        account_id: str,
        name: str,
        questions: list[dict[str, Any]],
        privacy_policy_url: str,
        *,
        privacy_policy_link_text: str | None = None,
        follow_up_action_url: str | None = None,
        locale: str | None = None,
        thank_you_title: str | None = None,
        thank_you_body: str | None = None,
        thank_you_button_text: str | None = None,
        thank_you_button_type: str | None = None,
        thank_you_website_url: str | None = None,
        is_optimized_for_quality: bool | None = None,
    ) -> dict[str, Any]:
        """Create a lead form (async)"""
        payload = self._build_payload(
            account_id=account_id,
            name=name,
            questions=questions,
            privacy_policy_url=privacy_policy_url,
            privacy_policy_link_text=privacy_policy_link_text,
            follow_up_action_url=follow_up_action_url,
            locale=locale,
            thank_you_title=thank_you_title,
            thank_you_body=thank_you_body,
            thank_you_button_text=thank_you_button_text,
            thank_you_button_type=thank_you_button_type,
            thank_you_website_url=thank_you_website_url,
            is_optimized_for_quality=is_optimized_for_quality,
        )
        return await self._client._apost("/v1/ads/lead-forms", data=payload)

    async def aget_lead_form(self, form_id: str, account_id: str) -> dict[str, Any]:
        """Get a lead form (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget(f"/v1/ads/lead-forms/{form_id}", params=params)

    async def aarchive_lead_form(self, form_id: str, account_id: str) -> dict[str, Any]:
        """Archive a lead form (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._adelete(
            f"/v1/ads/lead-forms/{form_id}", params=params
        )

    async def alist_form_leads(
        self,
        form_id: str,
        account_id: str,
        *,
        limit: int | None = 25,
        cursor: str | None = None,
        since: int | None = None,
    ) -> dict[str, Any]:
        """List leads for a single form (async)"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
            since=since,
        )
        return await self._client._aget(
            f"/v1/ads/lead-forms/{form_id}/leads", params=params
        )

    async def acreate_test_lead(
        self, form_id: str, account_id: str, field_data: list[dict[str, Any]]
    ) -> dict[str, Any]:
        """Create a test lead (async)"""
        payload = self._build_payload(
            account_id=account_id,
            field_data=field_data,
        )
        return await self._client._apost(
            f"/v1/ads/lead-forms/{form_id}/test-leads", data=payload
        )
