"""
Auto-generated lead_forms resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class LeadFormsResource:
    """
    lead_forms operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None values."""

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def list_lead_forms(
        self, account_id: str, *, limit: int | None = 25, cursor: str | None = None
    ) -> dict[str, Any]:
        """List Meta Lead Gen Forms"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
        )
        return self._client._get("/v1/ads/lead-forms", params=params)

    def create_lead_form(self) -> dict[str, Any]:
        """Create a Meta Lead Gen Form"""
        return self._client._post("/v1/ads/lead-forms")

    def get_lead_form(self, form_id: str, account_id: str) -> dict[str, Any]:
        """Get a Lead Gen Form"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get(f"/v1/ads/lead-forms/{form_id}", params=params)

    def update_lead_form(
        self, form_id: str, account_id: str, status: str
    ) -> dict[str, Any]:
        """Update a Lead Gen Form (status only)"""
        payload = self._build_payload(
            account_id=account_id,
            status=status,
        )
        return self._client._patch(f"/v1/ads/lead-forms/{form_id}", data=payload)

    def delete_lead_form(self, form_id: str, account_id: str) -> dict[str, Any]:
        """Delete a Lead Gen Form"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._delete(f"/v1/ads/lead-forms/{form_id}", params=params)

    def list_lead_form_leads(
        self,
        form_id: str,
        account_id: str,
        *,
        limit: int | None = 25,
        cursor: str | None = None,
        since: int | None = None,
    ) -> dict[str, Any]:
        """List submitted leads for a form"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
            since=since,
        )
        return self._client._get(f"/v1/ads/lead-forms/{form_id}/leads", params=params)

    def create_lead_form_test_lead(
        self, form_id: str, account_id: str, field_data: list[dict[str, Any]]
    ) -> dict[str, Any]:
        """Create a synthetic test lead"""
        payload = self._build_payload(
            account_id=account_id,
            field_data=field_data,
        )
        return self._client._post(
            f"/v1/ads/lead-forms/{form_id}/test-leads", data=payload
        )

    def delete_lead_form_test_lead(
        self, form_id: str, lead_id: str, account_id: str
    ) -> dict[str, Any]:
        """Delete a (test) lead"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._delete(
            f"/v1/ads/lead-forms/{form_id}/test-leads/{lead_id}", params=params
        )

    async def alist_lead_forms(
        self, account_id: str, *, limit: int | None = 25, cursor: str | None = None
    ) -> dict[str, Any]:
        """List Meta Lead Gen Forms (async)"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
        )
        return await self._client._aget("/v1/ads/lead-forms", params=params)

    async def acreate_lead_form(self) -> dict[str, Any]:
        """Create a Meta Lead Gen Form (async)"""
        return await self._client._apost("/v1/ads/lead-forms")

    async def aget_lead_form(self, form_id: str, account_id: str) -> dict[str, Any]:
        """Get a Lead Gen Form (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget(f"/v1/ads/lead-forms/{form_id}", params=params)

    async def aupdate_lead_form(
        self, form_id: str, account_id: str, status: str
    ) -> dict[str, Any]:
        """Update a Lead Gen Form (status only) (async)"""
        payload = self._build_payload(
            account_id=account_id,
            status=status,
        )
        return await self._client._apatch(f"/v1/ads/lead-forms/{form_id}", data=payload)

    async def adelete_lead_form(self, form_id: str, account_id: str) -> dict[str, Any]:
        """Delete a Lead Gen Form (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._adelete(
            f"/v1/ads/lead-forms/{form_id}", params=params
        )

    async def alist_lead_form_leads(
        self,
        form_id: str,
        account_id: str,
        *,
        limit: int | None = 25,
        cursor: str | None = None,
        since: int | None = None,
    ) -> dict[str, Any]:
        """List submitted leads for a form (async)"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
            since=since,
        )
        return await self._client._aget(
            f"/v1/ads/lead-forms/{form_id}/leads", params=params
        )

    async def acreate_lead_form_test_lead(
        self, form_id: str, account_id: str, field_data: list[dict[str, Any]]
    ) -> dict[str, Any]:
        """Create a synthetic test lead (async)"""
        payload = self._build_payload(
            account_id=account_id,
            field_data=field_data,
        )
        return await self._client._apost(
            f"/v1/ads/lead-forms/{form_id}/test-leads", data=payload
        )

    async def adelete_lead_form_test_lead(
        self, form_id: str, lead_id: str, account_id: str
    ) -> dict[str, Any]:
        """Delete a (test) lead (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._adelete(
            f"/v1/ads/lead-forms/{form_id}/test-leads/{lead_id}", params=params
        )
