"""
Auto-generated logs resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from datetime import datetime

    from ..client.base import BaseClient


class LogsResource:
    """
    Publishing logs for debugging.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.
        """

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None and v != ""}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def list_logs(
        self,
        *,
        type: str | None = "publishing",
        status: str | None = None,
        platform: str | None = None,
        action: str | None = None,
        search: str | None = None,
        days: int | None = 90,
        limit: int | None = 50,
        skip: int | None = 0,
        account_id: str | None = None,
        event: str | None = None,
        request_id: str | None = None,
        from_: datetime | str | None = None,
        to: datetime | str | None = None,
        status_code: int | None = None,
        api_key_id: str | None = None,
        include_read_receipts: bool | None = False,
    ) -> dict[str, Any]:
        """List activity logs"""
        params = self._build_params(
            type=type,
            status=status,
            platform=platform,
            action=action,
            search=search,
            days=days,
            limit=limit,
            skip=skip,
            account_id=account_id,
            event=event,
            request_id=request_id,
            from_=from_,
            to=to,
            status_code=status_code,
            api_key_id=api_key_id,
            include_read_receipts=include_read_receipts,
        )
        return self._client._get("/v1/logs", params=params)

    async def alist_logs(
        self,
        *,
        type: str | None = "publishing",
        status: str | None = None,
        platform: str | None = None,
        action: str | None = None,
        search: str | None = None,
        days: int | None = 90,
        limit: int | None = 50,
        skip: int | None = 0,
        account_id: str | None = None,
        event: str | None = None,
        request_id: str | None = None,
        from_: datetime | str | None = None,
        to: datetime | str | None = None,
        status_code: int | None = None,
        api_key_id: str | None = None,
        include_read_receipts: bool | None = False,
    ) -> dict[str, Any]:
        """List activity logs (async)"""
        params = self._build_params(
            type=type,
            status=status,
            platform=platform,
            action=action,
            search=search,
            days=days,
            limit=limit,
            skip=skip,
            account_id=account_id,
            event=event,
            request_id=request_id,
            from_=from_,
            to=to,
            status_code=status_code,
            api_key_id=api_key_id,
            include_read_receipts=include_read_receipts,
        )
        return await self._client._aget("/v1/logs", params=params)
