"""
Auto-generated mentions resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class MentionsResource:
    """
    mentions operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.
        """

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None and v != ""}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def list_inbox_mentions(
        self,
        *,
        account_id: str | None = None,
        profile_id: str | None = None,
        sort_order: str | None = "desc",
        limit: int | None = 25,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """List mentions"""
        params = self._build_params(
            account_id=account_id,
            profile_id=profile_id,
            sort_order=sort_order,
            limit=limit,
            cursor=cursor,
        )
        return self._client._get("/v1/inbox/mentions", params=params)

    def reply_to_mention(
        self,
        account_id: str,
        media_id: str,
        message: str,
        *,
        comment_id: str | None = None,
    ) -> dict[str, Any]:
        """Reply to a mention"""
        payload = self._build_payload(
            account_id=account_id,
            media_id=media_id,
            comment_id=comment_id,
            message=message,
        )
        return self._client._post("/v1/inbox/mentions/reply", data=payload)

    async def alist_inbox_mentions(
        self,
        *,
        account_id: str | None = None,
        profile_id: str | None = None,
        sort_order: str | None = "desc",
        limit: int | None = 25,
        cursor: str | None = None,
    ) -> dict[str, Any]:
        """List mentions (async)"""
        params = self._build_params(
            account_id=account_id,
            profile_id=profile_id,
            sort_order=sort_order,
            limit=limit,
            cursor=cursor,
        )
        return await self._client._aget("/v1/inbox/mentions", params=params)

    async def areply_to_mention(
        self,
        account_id: str,
        media_id: str,
        message: str,
        *,
        comment_id: str | None = None,
    ) -> dict[str, Any]:
        """Reply to a mention (async)"""
        payload = self._build_payload(
            account_id=account_id,
            media_id=media_id,
            comment_id=comment_id,
            message=message,
        )
        return await self._client._apost("/v1/inbox/mentions/reply", data=payload)
