"""
Auto-generated messaging_ads resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class MessagingAdsResource:
    """
    messaging_ads operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.

        Enum members are unwrapped to their value: httpx serializes params
        via str(), which yields "ClassName.MEMBER" for Enum members, so
        e.g. ``status=PostStatus.FAILED`` would otherwise reach the API as
        ``status=PostStatus.FAILED`` instead of ``status=failed``.
        """
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None or v == "":
                continue
            result[to_camel(k)] = v
        return result

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values. Enum members are
        unwrapped to their value so JSON bodies carry e.g. "failed" rather
        than a raw Enum member (plain Enum members are not JSON-serializable).
        """
        from datetime import datetime
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def create_messaging_ad(self) -> dict[str, Any]:
        """Create click-to-message ad (WhatsApp / Messenger / Instagram Direct)"""
        return self._client._post("/v1/ads/messaging")

    def create_call_ad(self) -> dict[str, Any]:
        """Create Click-to-Call ad"""
        return self._client._post("/v1/ads/call")

    def create_ctwa_ad(self) -> dict[str, Any]:
        """Create Click-to-WhatsApp ad (deprecated)"""
        return self._client._post("/v1/ads/ctwa")

    async def acreate_messaging_ad(self) -> dict[str, Any]:
        """Create click-to-message ad (WhatsApp / Messenger / Instagram Direct) (async)"""
        return await self._client._apost("/v1/ads/messaging")

    async def acreate_call_ad(self) -> dict[str, Any]:
        """Create Click-to-Call ad (async)"""
        return await self._client._apost("/v1/ads/call")

    async def acreate_ctwa_ad(self) -> dict[str, Any]:
        """Create Click-to-WhatsApp ad (deprecated) (async)"""
        return await self._client._apost("/v1/ads/ctwa")
