"""
Auto-generated reddit resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class RedditResource:
    """
    Reddit search and feed.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.

        Enum members are unwrapped to their value: httpx serializes params
        via str(), which yields "ClassName.MEMBER" for Enum members, so
        e.g. ``status=PostStatus.FAILED`` would otherwise reach the API as
        ``status=PostStatus.FAILED`` instead of ``status=failed``.
        """
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None or v == "":
                continue
            result[to_camel(k)] = v
        return result

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values. Enum members are
        unwrapped to their value so JSON bodies carry e.g. "failed" rather
        than a raw Enum member (plain Enum members are not JSON-serializable).
        """
        from datetime import datetime
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def search_reddit(
        self,
        account_id: str,
        q: str,
        *,
        subreddit: str | None = None,
        restrict_sr: str | None = None,
        sort: str | None = "new",
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Search posts"""
        params = self._build_params(
            account_id=account_id,
            subreddit=subreddit,
            q=q,
            restrict_sr=restrict_sr,
            sort=sort,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/reddit/search", params=params)

    def get_reddit_feed(
        self,
        account_id: str,
        *,
        subreddit: str | None = None,
        sort: str | None = "hot",
        limit: int | None = 25,
        after: str | None = None,
        t: str | None = None,
    ) -> dict[str, Any]:
        """Get subreddit feed"""
        params = self._build_params(
            account_id=account_id,
            subreddit=subreddit,
            sort=sort,
            limit=limit,
            after=after,
            t=t,
        )
        return self._client._get("/v1/reddit/feed", params=params)

    async def asearch_reddit(
        self,
        account_id: str,
        q: str,
        *,
        subreddit: str | None = None,
        restrict_sr: str | None = None,
        sort: str | None = "new",
        limit: int | None = 25,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Search posts (async)"""
        params = self._build_params(
            account_id=account_id,
            subreddit=subreddit,
            q=q,
            restrict_sr=restrict_sr,
            sort=sort,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/reddit/search", params=params)

    async def aget_reddit_feed(
        self,
        account_id: str,
        *,
        subreddit: str | None = None,
        sort: str | None = "hot",
        limit: int | None = 25,
        after: str | None = None,
        t: str | None = None,
    ) -> dict[str, Any]:
        """Get subreddit feed (async)"""
        params = self._build_params(
            account_id=account_id,
            subreddit=subreddit,
            sort=sort,
            limit=limit,
            after=after,
            t=t,
        )
        return await self._client._aget("/v1/reddit/feed", params=params)
