"""
Auto-generated usage resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from datetime import datetime

    from ..client.base import BaseClient


class UsageResource:
    """
    Get usage statistics.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.
        """

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None and v != ""}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def get_x_api_pricing(self) -> dict[str, Any]:
        """Get X/Twitter API pricing table"""
        return self._client._get("/v1/billing/x-pricing")

    def get_usage(self, *, reconcile: bool | None = None) -> dict[str, Any]:
        """Get plan and usage snapshot"""
        params = self._build_params(
            reconcile=reconcile,
        )
        return self._client._get("/v1/usage", params=params)

    def get_usage_stats(self, *, reconcile: bool | None = None) -> dict[str, Any]:
        """Get plan and usage stats"""
        params = self._build_params(
            reconcile=reconcile,
        )
        return self._client._get("/v1/usage-stats", params=params)

    def get_calls_usage(
        self,
        *,
        since: datetime | str | None = None,
        until: datetime | str | None = None,
        channel: str | None = None,
        number: str | None = None,
        group_by: str | None = None,
    ) -> dict[str, Any]:
        """Calling usage (volumes + billable cost)"""
        params = self._build_params(
            since=since,
            until=until,
            channel=channel,
            number=number,
            group_by=group_by,
        )
        return self._client._get("/v1/usage/calls", params=params)

    def get_sms_usage(
        self,
        *,
        since: datetime | str | None = None,
        until: datetime | str | None = None,
        number: str | None = None,
        group_by: str | None = None,
    ) -> dict[str, Any]:
        """SMS usage (volumes)"""
        params = self._build_params(
            since=since,
            until=until,
            number=number,
            group_by=group_by,
        )
        return self._client._get("/v1/usage/sms", params=params)

    async def aget_x_api_pricing(self) -> dict[str, Any]:
        """Get X/Twitter API pricing table (async)"""
        return await self._client._aget("/v1/billing/x-pricing")

    async def aget_usage(self, *, reconcile: bool | None = None) -> dict[str, Any]:
        """Get plan and usage snapshot (async)"""
        params = self._build_params(
            reconcile=reconcile,
        )
        return await self._client._aget("/v1/usage", params=params)

    async def aget_usage_stats(
        self, *, reconcile: bool | None = None
    ) -> dict[str, Any]:
        """Get plan and usage stats (async)"""
        params = self._build_params(
            reconcile=reconcile,
        )
        return await self._client._aget("/v1/usage-stats", params=params)

    async def aget_calls_usage(
        self,
        *,
        since: datetime | str | None = None,
        until: datetime | str | None = None,
        channel: str | None = None,
        number: str | None = None,
        group_by: str | None = None,
    ) -> dict[str, Any]:
        """Calling usage (volumes + billable cost) (async)"""
        params = self._build_params(
            since=since,
            until=until,
            channel=channel,
            number=number,
            group_by=group_by,
        )
        return await self._client._aget("/v1/usage/calls", params=params)

    async def aget_sms_usage(
        self,
        *,
        since: datetime | str | None = None,
        until: datetime | str | None = None,
        number: str | None = None,
        group_by: str | None = None,
    ) -> dict[str, Any]:
        """SMS usage (volumes) (async)"""
        params = self._build_params(
            since=since,
            until=until,
            number=number,
            group_by=group_by,
        )
        return await self._client._aget("/v1/usage/sms", params=params)
