"""
Auto-generated whatsapp_sandbox resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class WhatsappSandboxResource:
    """
    whatsapp_sandbox operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.
        """

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None and v != ""}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def list_whats_app_sandbox_sessions(self) -> dict[str, Any]:
        """List your sandbox sessions"""
        return self._client._get("/v1/whatsapp/sandbox/sessions")

    def create_whats_app_sandbox_session(self, phone: str) -> dict[str, Any]:
        """Start a sandbox activation"""
        payload = self._build_payload(
            phone=phone,
        )
        return self._client._post("/v1/whatsapp/sandbox/sessions", data=payload)

    def delete_whats_app_sandbox_session(self, session_id: str) -> dict[str, Any]:
        """Revoke a sandbox session"""
        return self._client._delete(f"/v1/whatsapp/sandbox/sessions/{session_id}")

    async def alist_whats_app_sandbox_sessions(self) -> dict[str, Any]:
        """List your sandbox sessions (async)"""
        return await self._client._aget("/v1/whatsapp/sandbox/sessions")

    async def acreate_whats_app_sandbox_session(self, phone: str) -> dict[str, Any]:
        """Start a sandbox activation (async)"""
        payload = self._build_payload(
            phone=phone,
        )
        return await self._client._apost("/v1/whatsapp/sandbox/sessions", data=payload)

    async def adelete_whats_app_sandbox_session(
        self, session_id: str
    ) -> dict[str, Any]:
        """Revoke a sandbox session (async)"""
        return await self._client._adelete(
            f"/v1/whatsapp/sandbox/sessions/{session_id}"
        )
