"""
Auto-generated whatsapp_phone_numbers resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class WhatsappPhoneNumbersResource:
    """
    whatsapp_phone_numbers operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.
        """

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None and v != ""}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def get_whats_app_number_info(self, account_id: str) -> dict[str, Any]:
        """Get number status"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get("/v1/whatsapp/number-info", params=params)

    def get_whats_app_phone_numbers(
        self, *, status: str | None = None, profile_id: str | None = None
    ) -> dict[str, Any]:
        """List phone numbers"""
        params = self._build_params(
            status=status,
            profile_id=profile_id,
        )
        return self._client._get("/v1/whatsapp/phone-numbers", params=params)

    def purchase_whats_app_phone_number(
        self,
        profile_id: str,
        *,
        country: str | None = "US",
        purchase_intent_id: str | None = None,
        allow_multiple: bool | None = False,
    ) -> dict[str, Any]:
        """Purchase phone number"""
        payload = self._build_payload(
            profile_id=profile_id,
            country=country,
            purchase_intent_id=purchase_intent_id,
            allow_multiple=allow_multiple,
        )
        return self._client._post("/v1/whatsapp/phone-numbers/purchase", data=payload)

    def list_whats_app_number_countries(self) -> dict[str, Any]:
        """List offerable number countries"""
        return self._client._get("/v1/whatsapp/phone-numbers/countries")

    def search_available_whats_app_numbers(
        self,
        *,
        country: str | None = "US",
        type: str | None = None,
        prefix: str | None = None,
        locality: str | None = None,
        contains: str | None = None,
        limit: int | None = 20,
    ) -> dict[str, Any]:
        """Search available numbers"""
        params = self._build_params(
            country=country,
            type=type,
            prefix=prefix,
            locality=locality,
            contains=contains,
            limit=limit,
        )
        return self._client._get("/v1/whatsapp/phone-numbers/available", params=params)

    def check_whats_app_number_availability(self, country: str) -> dict[str, Any]:
        """Check country availability"""
        params = self._build_params(
            country=country,
        )
        return self._client._get(
            "/v1/whatsapp/phone-numbers/availability", params=params
        )

    def get_whats_app_number_kyc_form(
        self, country: str, profile_id: str
    ) -> dict[str, Any]:
        """Get KYC form spec"""
        params = self._build_params(
            country=country,
            profile_id=profile_id,
        )
        return self._client._get("/v1/whatsapp/phone-numbers/kyc", params=params)

    def submit_whats_app_number_kyc(
        self,
        profile_id: str,
        country: str,
        *,
        submission_id: str | None = None,
        quantity: int | None = 1,
        reuse: bool | None = None,
        reuse_from: str | None = None,
        end_user_first_name: str | None = None,
        end_user_last_name: str | None = None,
        values: dict[str, Any] | None = None,
        documents: list[Any] | None = None,
        address: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Submit KYC"""
        payload = self._build_payload(
            profile_id=profile_id,
            country=country,
            submission_id=submission_id,
            quantity=quantity,
            reuse=reuse,
            reuse_from=reuse_from,
            end_user_first_name=end_user_first_name,
            end_user_last_name=end_user_last_name,
            values=values,
            documents=documents,
            address=address,
        )
        return self._client._post("/v1/whatsapp/phone-numbers/kyc", data=payload)

    def upload_whats_app_number_kyc_document(self, x_filename: str) -> dict[str, Any]:
        """Upload a KYC document"""
        return self._client._post("/v1/whatsapp/phone-numbers/kyc/upload-document")

    def validate_whats_app_number_kyc_address(
        self,
        country: str,
        street_address: str,
        locality: str,
        postal_code: str,
        *,
        administrative_area: str | None = None,
    ) -> dict[str, Any]:
        """Pre-validate KYC address"""
        payload = self._build_payload(
            country=country,
            street_address=street_address,
            locality=locality,
            administrative_area=administrative_area,
            postal_code=postal_code,
        )
        return self._client._post(
            "/v1/whatsapp/phone-numbers/kyc/validate-address", data=payload
        )

    def create_whats_app_number_kyc_link(
        self,
        profile_id: str,
        country: str,
        *,
        branding: dict[str, Any] | None = None,
        redirect_url: str | None = None,
    ) -> dict[str, Any]:
        """Create a hosted KYC link"""
        payload = self._build_payload(
            profile_id=profile_id,
            country=country,
            branding=branding,
            redirect_url=redirect_url,
        )
        return self._client._post("/v1/whatsapp/phone-numbers/kyc/share", data=payload)

    def get_whats_app_number_remediation(self, id: str) -> dict[str, Any]:
        """Get declined requirements"""
        return self._client._get(f"/v1/whatsapp/phone-numbers/{id}/remediate")

    def remediate_whats_app_number(
        self,
        id: str,
        *,
        values: dict[str, Any] | None = None,
        documents: list[Any] | None = None,
        address: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Resubmit a declined number"""
        payload = self._build_payload(
            values=values,
            documents=documents,
            address=address,
        )
        return self._client._post(
            f"/v1/whatsapp/phone-numbers/{id}/remediate", data=payload
        )

    def get_whats_app_phone_number(self, phone_number_id: str) -> dict[str, Any]:
        """Get phone number"""
        return self._client._get(f"/v1/whatsapp/phone-numbers/{phone_number_id}")

    def release_whats_app_phone_number(self, phone_number_id: str) -> dict[str, Any]:
        """Release phone number"""
        return self._client._delete(f"/v1/whatsapp/phone-numbers/{phone_number_id}")

    async def aget_whats_app_number_info(self, account_id: str) -> dict[str, Any]:
        """Get number status (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget("/v1/whatsapp/number-info", params=params)

    async def aget_whats_app_phone_numbers(
        self, *, status: str | None = None, profile_id: str | None = None
    ) -> dict[str, Any]:
        """List phone numbers (async)"""
        params = self._build_params(
            status=status,
            profile_id=profile_id,
        )
        return await self._client._aget("/v1/whatsapp/phone-numbers", params=params)

    async def apurchase_whats_app_phone_number(
        self,
        profile_id: str,
        *,
        country: str | None = "US",
        purchase_intent_id: str | None = None,
        allow_multiple: bool | None = False,
    ) -> dict[str, Any]:
        """Purchase phone number (async)"""
        payload = self._build_payload(
            profile_id=profile_id,
            country=country,
            purchase_intent_id=purchase_intent_id,
            allow_multiple=allow_multiple,
        )
        return await self._client._apost(
            "/v1/whatsapp/phone-numbers/purchase", data=payload
        )

    async def alist_whats_app_number_countries(self) -> dict[str, Any]:
        """List offerable number countries (async)"""
        return await self._client._aget("/v1/whatsapp/phone-numbers/countries")

    async def asearch_available_whats_app_numbers(
        self,
        *,
        country: str | None = "US",
        type: str | None = None,
        prefix: str | None = None,
        locality: str | None = None,
        contains: str | None = None,
        limit: int | None = 20,
    ) -> dict[str, Any]:
        """Search available numbers (async)"""
        params = self._build_params(
            country=country,
            type=type,
            prefix=prefix,
            locality=locality,
            contains=contains,
            limit=limit,
        )
        return await self._client._aget(
            "/v1/whatsapp/phone-numbers/available", params=params
        )

    async def acheck_whats_app_number_availability(
        self, country: str
    ) -> dict[str, Any]:
        """Check country availability (async)"""
        params = self._build_params(
            country=country,
        )
        return await self._client._aget(
            "/v1/whatsapp/phone-numbers/availability", params=params
        )

    async def aget_whats_app_number_kyc_form(
        self, country: str, profile_id: str
    ) -> dict[str, Any]:
        """Get KYC form spec (async)"""
        params = self._build_params(
            country=country,
            profile_id=profile_id,
        )
        return await self._client._aget("/v1/whatsapp/phone-numbers/kyc", params=params)

    async def asubmit_whats_app_number_kyc(
        self,
        profile_id: str,
        country: str,
        *,
        submission_id: str | None = None,
        quantity: int | None = 1,
        reuse: bool | None = None,
        reuse_from: str | None = None,
        end_user_first_name: str | None = None,
        end_user_last_name: str | None = None,
        values: dict[str, Any] | None = None,
        documents: list[Any] | None = None,
        address: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Submit KYC (async)"""
        payload = self._build_payload(
            profile_id=profile_id,
            country=country,
            submission_id=submission_id,
            quantity=quantity,
            reuse=reuse,
            reuse_from=reuse_from,
            end_user_first_name=end_user_first_name,
            end_user_last_name=end_user_last_name,
            values=values,
            documents=documents,
            address=address,
        )
        return await self._client._apost("/v1/whatsapp/phone-numbers/kyc", data=payload)

    async def aupload_whats_app_number_kyc_document(
        self, x_filename: str
    ) -> dict[str, Any]:
        """Upload a KYC document (async)"""
        return await self._client._apost(
            "/v1/whatsapp/phone-numbers/kyc/upload-document"
        )

    async def avalidate_whats_app_number_kyc_address(
        self,
        country: str,
        street_address: str,
        locality: str,
        postal_code: str,
        *,
        administrative_area: str | None = None,
    ) -> dict[str, Any]:
        """Pre-validate KYC address (async)"""
        payload = self._build_payload(
            country=country,
            street_address=street_address,
            locality=locality,
            administrative_area=administrative_area,
            postal_code=postal_code,
        )
        return await self._client._apost(
            "/v1/whatsapp/phone-numbers/kyc/validate-address", data=payload
        )

    async def acreate_whats_app_number_kyc_link(
        self,
        profile_id: str,
        country: str,
        *,
        branding: dict[str, Any] | None = None,
        redirect_url: str | None = None,
    ) -> dict[str, Any]:
        """Create a hosted KYC link (async)"""
        payload = self._build_payload(
            profile_id=profile_id,
            country=country,
            branding=branding,
            redirect_url=redirect_url,
        )
        return await self._client._apost(
            "/v1/whatsapp/phone-numbers/kyc/share", data=payload
        )

    async def aget_whats_app_number_remediation(self, id: str) -> dict[str, Any]:
        """Get declined requirements (async)"""
        return await self._client._aget(f"/v1/whatsapp/phone-numbers/{id}/remediate")

    async def aremediate_whats_app_number(
        self,
        id: str,
        *,
        values: dict[str, Any] | None = None,
        documents: list[Any] | None = None,
        address: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Resubmit a declined number (async)"""
        payload = self._build_payload(
            values=values,
            documents=documents,
            address=address,
        )
        return await self._client._apost(
            f"/v1/whatsapp/phone-numbers/{id}/remediate", data=payload
        )

    async def aget_whats_app_phone_number(self, phone_number_id: str) -> dict[str, Any]:
        """Get phone number (async)"""
        return await self._client._aget(f"/v1/whatsapp/phone-numbers/{phone_number_id}")

    async def arelease_whats_app_phone_number(
        self, phone_number_id: str
    ) -> dict[str, Any]:
        """Release phone number (async)"""
        return await self._client._adelete(
            f"/v1/whatsapp/phone-numbers/{phone_number_id}"
        )
