"""
Auto-generated whatsapp resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class WhatsappResource:
    """
    whatsapp operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.

        Enum members are unwrapped to their value: httpx serializes params
        via str(), which yields "ClassName.MEMBER" for Enum members, so
        e.g. ``status=PostStatus.FAILED`` would otherwise reach the API as
        ``status=PostStatus.FAILED`` instead of ``status=failed``.
        """
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None or v == "":
                continue
            result[to_camel(k)] = v
        return result

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values. Enum members are
        unwrapped to their value so JSON bodies carry e.g. "failed" rather
        than a raw Enum member (plain Enum members are not JSON-serializable).
        """
        from datetime import datetime
        from enum import Enum

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if isinstance(v, Enum):
                v = v.value
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def register_whats_app_number(
        self, account_id: str, *, pin: str | None = None
    ) -> dict[str, Any]:
        """Register a connected WhatsApp number on the Cloud API"""
        payload = self._build_payload(
            pin=pin,
        )
        return self._client._post(
            f"/v1/accounts/{account_id}/whatsapp/register", data=payload
        )

    def get_whats_app_media(self, media_id: str, account_id: str) -> dict[str, Any]:
        """Download WhatsApp media"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get(f"/v1/whatsapp/media/{media_id}", params=params)

    def get_whats_app_templates(self, account_id: str) -> dict[str, Any]:
        """List templates"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get("/v1/whatsapp/templates", params=params)

    def create_whats_app_template(
        self,
        account_id: str,
        name: str,
        category: str,
        language: str,
        *,
        parameter_format: str | None = None,
        components: list[Any] | None = None,
        library_template_name: str | None = None,
        library_template_body_inputs: dict[str, Any] | None = None,
        library_template_button_inputs: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Create template"""
        payload = self._build_payload(
            account_id=account_id,
            name=name,
            category=category,
            language=language,
            parameter_format=parameter_format,
            components=components,
            library_template_name=library_template_name,
            library_template_body_inputs=library_template_body_inputs,
            library_template_button_inputs=library_template_button_inputs,
        )
        return self._client._post("/v1/whatsapp/templates", data=payload)

    def get_whats_app_template(
        self, template_name: str, account_id: str
    ) -> dict[str, Any]:
        """Get template"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get(
            f"/v1/whatsapp/templates/{template_name}", params=params
        )

    def update_whats_app_template(
        self, template_name: str, account_id: str, components: list[Any]
    ) -> dict[str, Any]:
        """Update template"""
        payload = self._build_payload(
            account_id=account_id,
            components=components,
        )
        return self._client._patch(
            f"/v1/whatsapp/templates/{template_name}", data=payload
        )

    def delete_whats_app_template(
        self, template_name: str, account_id: str
    ) -> dict[str, Any]:
        """Delete template"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._delete(
            f"/v1/whatsapp/templates/{template_name}", params=params
        )

    def get_whats_app_business_profile(self, account_id: str) -> dict[str, Any]:
        """Get business profile"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get("/v1/whatsapp/business-profile", params=params)

    def update_whats_app_business_profile(
        self,
        account_id: str,
        *,
        about: str | None = None,
        address: str | None = None,
        description: str | None = None,
        email: str | None = None,
        websites: list[str] | None = None,
        vertical: str | None = None,
        profile_picture_handle: str | None = None,
    ) -> dict[str, Any]:
        """Update business profile"""
        payload = self._build_payload(
            account_id=account_id,
            about=about,
            address=address,
            description=description,
            email=email,
            websites=websites,
            vertical=vertical,
            profile_picture_handle=profile_picture_handle,
        )
        return self._client._post("/v1/whatsapp/business-profile", data=payload)

    def upload_whats_app_profile_photo(
        self, account_id: str, url: str
    ) -> dict[str, Any]:
        """Upload profile picture"""
        payload = self._build_payload(
            account_id=account_id,
            url=url,
        )
        return self._client._post("/v1/whatsapp/business-profile/photo", data=payload)

    def get_whats_app_display_name(self, account_id: str) -> dict[str, Any]:
        """Get display name status"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get(
            "/v1/whatsapp/business-profile/display-name", params=params
        )

    def update_whats_app_display_name(
        self, account_id: str, display_name: str
    ) -> dict[str, Any]:
        """Request display name change"""
        payload = self._build_payload(
            account_id=account_id,
            display_name=display_name,
        )
        return self._client._post(
            "/v1/whatsapp/business-profile/display-name", data=payload
        )

    def get_whatsapp_business_username(self, account_id: str) -> dict[str, Any]:
        """Get business username"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get(
            "/v1/whatsapp/business-profile/username", params=params
        )

    def set_whatsapp_business_username(
        self, account_id: str, username: str, *, transfer_action: str | None = "none"
    ) -> dict[str, Any]:
        """Set business username"""
        payload = self._build_payload(
            account_id=account_id,
            username=username,
            transfer_action=transfer_action,
        )
        return self._client._post(
            "/v1/whatsapp/business-profile/username", data=payload
        )

    def delete_whatsapp_business_username(self, account_id: str) -> dict[str, Any]:
        """Delete business username"""
        return self._client._delete("/v1/whatsapp/business-profile/username")

    def get_whatsapp_business_username_suggestions(
        self, account_id: str
    ) -> dict[str, Any]:
        """Get username suggestions"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get(
            "/v1/whatsapp/business-profile/username/suggestions", params=params
        )

    def get_whats_app_block_status(self, account_id: str, user: str) -> dict[str, Any]:
        """Check if a user is blocked"""
        params = self._build_params(
            account_id=account_id,
            user=user,
        )
        return self._client._get("/v1/whatsapp/block-users/status", params=params)

    def get_whats_app_blocked_users(
        self, account_id: str, *, limit: int | None = None, after: str | None = None
    ) -> dict[str, Any]:
        """List blocked users"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/whatsapp/block-users", params=params)

    def block_whats_app_users(
        self, account_id: str, users: list[str]
    ) -> dict[str, Any]:
        """Block users"""
        payload = self._build_payload(
            account_id=account_id,
            users=users,
        )
        return self._client._post("/v1/whatsapp/block-users", data=payload)

    def unblock_whats_app_users(
        self, account_id: str, users: list[str]
    ) -> dict[str, Any]:
        """Unblock users"""
        return self._client._delete("/v1/whatsapp/block-users")

    def get_whats_app_dataset(self, account_id: str) -> dict[str, Any]:
        """Get CTWA conversions dataset"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get("/v1/whatsapp/dataset", params=params)

    def create_whats_app_dataset(self, account_id: str) -> dict[str, Any]:
        """Provision CTWA dataset"""
        payload = self._build_payload(
            account_id=account_id,
        )
        return self._client._post("/v1/whatsapp/dataset", data=payload)

    def list_whats_app_group_chats(
        self, account_id: str, *, limit: int | None = 25, after: str | None = None
    ) -> dict[str, Any]:
        """List active groups"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            after=after,
        )
        return self._client._get("/v1/whatsapp/wa-groups", params=params)

    def create_whats_app_group_chat(
        self,
        account_id: str,
        subject: str,
        *,
        description: str | None = None,
        join_approval_mode: str | None = None,
    ) -> dict[str, Any]:
        """Create group"""
        payload = self._build_payload(
            account_id=account_id,
            subject=subject,
            description=description,
            join_approval_mode=join_approval_mode,
        )
        return self._client._post("/v1/whatsapp/wa-groups", data=payload)

    def get_whats_app_group_chat(
        self, group_id: str, account_id: str
    ) -> dict[str, Any]:
        """Get group info"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get(f"/v1/whatsapp/wa-groups/{group_id}", params=params)

    def update_whats_app_group_chat(
        self,
        group_id: str,
        account_id: str,
        *,
        subject: str | None = None,
        description: str | None = None,
        join_approval_mode: str | None = None,
    ) -> dict[str, Any]:
        """Update group settings"""
        params = self._build_params(
            account_id=account_id,
        )
        payload = self._build_payload(
            subject=subject,
            description=description,
            join_approval_mode=join_approval_mode,
        )
        return self._client._post(
            f"/v1/whatsapp/wa-groups/{group_id}", data=payload, params=params
        )

    def delete_whats_app_group_chat(
        self, group_id: str, account_id: str
    ) -> dict[str, Any]:
        """Delete group"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._delete(f"/v1/whatsapp/wa-groups/{group_id}", params=params)

    def add_whats_app_group_participants(
        self, group_id: str, account_id: str, phone_numbers: list[str]
    ) -> dict[str, Any]:
        """Add participants"""
        params = self._build_params(
            account_id=account_id,
        )
        payload = self._build_payload(
            phone_numbers=phone_numbers,
        )
        return self._client._post(
            f"/v1/whatsapp/wa-groups/{group_id}/participants",
            data=payload,
            params=params,
        )

    def remove_whats_app_group_participants(
        self, group_id: str, account_id: str, phone_numbers: list[str]
    ) -> dict[str, Any]:
        """Remove participants"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._delete(
            f"/v1/whatsapp/wa-groups/{group_id}/participants", params=params
        )

    def create_whats_app_group_invite_link(
        self, group_id: str, account_id: str
    ) -> dict[str, Any]:
        """Create invite link"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._post(
            f"/v1/whatsapp/wa-groups/{group_id}/invite-link", params=params
        )

    def list_whats_app_group_join_requests(
        self, group_id: str, account_id: str
    ) -> dict[str, Any]:
        """List join requests"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._get(
            f"/v1/whatsapp/wa-groups/{group_id}/join-requests", params=params
        )

    def approve_whats_app_group_join_requests(
        self, group_id: str, account_id: str, phone_numbers: list[str]
    ) -> dict[str, Any]:
        """Approve join requests"""
        params = self._build_params(
            account_id=account_id,
        )
        payload = self._build_payload(
            phone_numbers=phone_numbers,
        )
        return self._client._post(
            f"/v1/whatsapp/wa-groups/{group_id}/join-requests",
            data=payload,
            params=params,
        )

    def reject_whats_app_group_join_requests(
        self, group_id: str, account_id: str, phone_numbers: list[str]
    ) -> dict[str, Any]:
        """Reject join requests"""
        params = self._build_params(
            account_id=account_id,
        )
        return self._client._delete(
            f"/v1/whatsapp/wa-groups/{group_id}/join-requests", params=params
        )

    def list_whats_app_conversions(
        self, account_id: str, *, limit: int | None = 50
    ) -> dict[str, Any]:
        """List conversion events"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
        )
        return self._client._get("/v1/whatsapp/conversions", params=params)

    def send_whats_app_conversion(
        self,
        account_id: str,
        event_name: str,
        event_id: str,
        *,
        event_time: float | None = None,
        conversation_id: str | None = None,
        phone_e164: str | None = None,
        value: float | None = None,
        currency: str | None = None,
        content_ids: list[str] | None = None,
        email: str | None = None,
        external_id: str | None = None,
        test_code: str | None = None,
    ) -> dict[str, Any]:
        """Send WhatsApp conversion event"""
        payload = self._build_payload(
            account_id=account_id,
            event_name=event_name,
            event_time=event_time,
            event_id=event_id,
            conversation_id=conversation_id,
            phone_e164=phone_e164,
            value=value,
            currency=currency,
            content_ids=content_ids,
            email=email,
            external_id=external_id,
            test_code=test_code,
        )
        return self._client._post("/v1/whatsapp/conversions", data=payload)

    async def aregister_whats_app_number(
        self, account_id: str, *, pin: str | None = None
    ) -> dict[str, Any]:
        """Register a connected WhatsApp number on the Cloud API (async)"""
        payload = self._build_payload(
            pin=pin,
        )
        return await self._client._apost(
            f"/v1/accounts/{account_id}/whatsapp/register", data=payload
        )

    async def aget_whats_app_media(
        self, media_id: str, account_id: str
    ) -> dict[str, Any]:
        """Download WhatsApp media (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget(f"/v1/whatsapp/media/{media_id}", params=params)

    async def aget_whats_app_templates(self, account_id: str) -> dict[str, Any]:
        """List templates (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget("/v1/whatsapp/templates", params=params)

    async def acreate_whats_app_template(
        self,
        account_id: str,
        name: str,
        category: str,
        language: str,
        *,
        parameter_format: str | None = None,
        components: list[Any] | None = None,
        library_template_name: str | None = None,
        library_template_body_inputs: dict[str, Any] | None = None,
        library_template_button_inputs: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Create template (async)"""
        payload = self._build_payload(
            account_id=account_id,
            name=name,
            category=category,
            language=language,
            parameter_format=parameter_format,
            components=components,
            library_template_name=library_template_name,
            library_template_body_inputs=library_template_body_inputs,
            library_template_button_inputs=library_template_button_inputs,
        )
        return await self._client._apost("/v1/whatsapp/templates", data=payload)

    async def aget_whats_app_template(
        self, template_name: str, account_id: str
    ) -> dict[str, Any]:
        """Get template (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget(
            f"/v1/whatsapp/templates/{template_name}", params=params
        )

    async def aupdate_whats_app_template(
        self, template_name: str, account_id: str, components: list[Any]
    ) -> dict[str, Any]:
        """Update template (async)"""
        payload = self._build_payload(
            account_id=account_id,
            components=components,
        )
        return await self._client._apatch(
            f"/v1/whatsapp/templates/{template_name}", data=payload
        )

    async def adelete_whats_app_template(
        self, template_name: str, account_id: str
    ) -> dict[str, Any]:
        """Delete template (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._adelete(
            f"/v1/whatsapp/templates/{template_name}", params=params
        )

    async def aget_whats_app_business_profile(self, account_id: str) -> dict[str, Any]:
        """Get business profile (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget("/v1/whatsapp/business-profile", params=params)

    async def aupdate_whats_app_business_profile(
        self,
        account_id: str,
        *,
        about: str | None = None,
        address: str | None = None,
        description: str | None = None,
        email: str | None = None,
        websites: list[str] | None = None,
        vertical: str | None = None,
        profile_picture_handle: str | None = None,
    ) -> dict[str, Any]:
        """Update business profile (async)"""
        payload = self._build_payload(
            account_id=account_id,
            about=about,
            address=address,
            description=description,
            email=email,
            websites=websites,
            vertical=vertical,
            profile_picture_handle=profile_picture_handle,
        )
        return await self._client._apost("/v1/whatsapp/business-profile", data=payload)

    async def aupload_whats_app_profile_photo(
        self, account_id: str, url: str
    ) -> dict[str, Any]:
        """Upload profile picture (async)"""
        payload = self._build_payload(
            account_id=account_id,
            url=url,
        )
        return await self._client._apost(
            "/v1/whatsapp/business-profile/photo", data=payload
        )

    async def aget_whats_app_display_name(self, account_id: str) -> dict[str, Any]:
        """Get display name status (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget(
            "/v1/whatsapp/business-profile/display-name", params=params
        )

    async def aupdate_whats_app_display_name(
        self, account_id: str, display_name: str
    ) -> dict[str, Any]:
        """Request display name change (async)"""
        payload = self._build_payload(
            account_id=account_id,
            display_name=display_name,
        )
        return await self._client._apost(
            "/v1/whatsapp/business-profile/display-name", data=payload
        )

    async def aget_whatsapp_business_username(self, account_id: str) -> dict[str, Any]:
        """Get business username (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget(
            "/v1/whatsapp/business-profile/username", params=params
        )

    async def aset_whatsapp_business_username(
        self, account_id: str, username: str, *, transfer_action: str | None = "none"
    ) -> dict[str, Any]:
        """Set business username (async)"""
        payload = self._build_payload(
            account_id=account_id,
            username=username,
            transfer_action=transfer_action,
        )
        return await self._client._apost(
            "/v1/whatsapp/business-profile/username", data=payload
        )

    async def adelete_whatsapp_business_username(
        self, account_id: str
    ) -> dict[str, Any]:
        """Delete business username (async)"""
        return await self._client._adelete("/v1/whatsapp/business-profile/username")

    async def aget_whatsapp_business_username_suggestions(
        self, account_id: str
    ) -> dict[str, Any]:
        """Get username suggestions (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget(
            "/v1/whatsapp/business-profile/username/suggestions", params=params
        )

    async def aget_whats_app_block_status(
        self, account_id: str, user: str
    ) -> dict[str, Any]:
        """Check if a user is blocked (async)"""
        params = self._build_params(
            account_id=account_id,
            user=user,
        )
        return await self._client._aget(
            "/v1/whatsapp/block-users/status", params=params
        )

    async def aget_whats_app_blocked_users(
        self, account_id: str, *, limit: int | None = None, after: str | None = None
    ) -> dict[str, Any]:
        """List blocked users (async)"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/whatsapp/block-users", params=params)

    async def ablock_whats_app_users(
        self, account_id: str, users: list[str]
    ) -> dict[str, Any]:
        """Block users (async)"""
        payload = self._build_payload(
            account_id=account_id,
            users=users,
        )
        return await self._client._apost("/v1/whatsapp/block-users", data=payload)

    async def aunblock_whats_app_users(
        self, account_id: str, users: list[str]
    ) -> dict[str, Any]:
        """Unblock users (async)"""
        return await self._client._adelete("/v1/whatsapp/block-users")

    async def aget_whats_app_dataset(self, account_id: str) -> dict[str, Any]:
        """Get CTWA conversions dataset (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget("/v1/whatsapp/dataset", params=params)

    async def acreate_whats_app_dataset(self, account_id: str) -> dict[str, Any]:
        """Provision CTWA dataset (async)"""
        payload = self._build_payload(
            account_id=account_id,
        )
        return await self._client._apost("/v1/whatsapp/dataset", data=payload)

    async def alist_whats_app_group_chats(
        self, account_id: str, *, limit: int | None = 25, after: str | None = None
    ) -> dict[str, Any]:
        """List active groups (async)"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            after=after,
        )
        return await self._client._aget("/v1/whatsapp/wa-groups", params=params)

    async def acreate_whats_app_group_chat(
        self,
        account_id: str,
        subject: str,
        *,
        description: str | None = None,
        join_approval_mode: str | None = None,
    ) -> dict[str, Any]:
        """Create group (async)"""
        payload = self._build_payload(
            account_id=account_id,
            subject=subject,
            description=description,
            join_approval_mode=join_approval_mode,
        )
        return await self._client._apost("/v1/whatsapp/wa-groups", data=payload)

    async def aget_whats_app_group_chat(
        self, group_id: str, account_id: str
    ) -> dict[str, Any]:
        """Get group info (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget(
            f"/v1/whatsapp/wa-groups/{group_id}", params=params
        )

    async def aupdate_whats_app_group_chat(
        self,
        group_id: str,
        account_id: str,
        *,
        subject: str | None = None,
        description: str | None = None,
        join_approval_mode: str | None = None,
    ) -> dict[str, Any]:
        """Update group settings (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        payload = self._build_payload(
            subject=subject,
            description=description,
            join_approval_mode=join_approval_mode,
        )
        return await self._client._apost(
            f"/v1/whatsapp/wa-groups/{group_id}", data=payload, params=params
        )

    async def adelete_whats_app_group_chat(
        self, group_id: str, account_id: str
    ) -> dict[str, Any]:
        """Delete group (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._adelete(
            f"/v1/whatsapp/wa-groups/{group_id}", params=params
        )

    async def aadd_whats_app_group_participants(
        self, group_id: str, account_id: str, phone_numbers: list[str]
    ) -> dict[str, Any]:
        """Add participants (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        payload = self._build_payload(
            phone_numbers=phone_numbers,
        )
        return await self._client._apost(
            f"/v1/whatsapp/wa-groups/{group_id}/participants",
            data=payload,
            params=params,
        )

    async def aremove_whats_app_group_participants(
        self, group_id: str, account_id: str, phone_numbers: list[str]
    ) -> dict[str, Any]:
        """Remove participants (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._adelete(
            f"/v1/whatsapp/wa-groups/{group_id}/participants", params=params
        )

    async def acreate_whats_app_group_invite_link(
        self, group_id: str, account_id: str
    ) -> dict[str, Any]:
        """Create invite link (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._apost(
            f"/v1/whatsapp/wa-groups/{group_id}/invite-link", params=params
        )

    async def alist_whats_app_group_join_requests(
        self, group_id: str, account_id: str
    ) -> dict[str, Any]:
        """List join requests (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._aget(
            f"/v1/whatsapp/wa-groups/{group_id}/join-requests", params=params
        )

    async def aapprove_whats_app_group_join_requests(
        self, group_id: str, account_id: str, phone_numbers: list[str]
    ) -> dict[str, Any]:
        """Approve join requests (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        payload = self._build_payload(
            phone_numbers=phone_numbers,
        )
        return await self._client._apost(
            f"/v1/whatsapp/wa-groups/{group_id}/join-requests",
            data=payload,
            params=params,
        )

    async def areject_whats_app_group_join_requests(
        self, group_id: str, account_id: str, phone_numbers: list[str]
    ) -> dict[str, Any]:
        """Reject join requests (async)"""
        params = self._build_params(
            account_id=account_id,
        )
        return await self._client._adelete(
            f"/v1/whatsapp/wa-groups/{group_id}/join-requests", params=params
        )

    async def alist_whats_app_conversions(
        self, account_id: str, *, limit: int | None = 50
    ) -> dict[str, Any]:
        """List conversion events (async)"""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
        )
        return await self._client._aget("/v1/whatsapp/conversions", params=params)

    async def asend_whats_app_conversion(
        self,
        account_id: str,
        event_name: str,
        event_id: str,
        *,
        event_time: float | None = None,
        conversation_id: str | None = None,
        phone_e164: str | None = None,
        value: float | None = None,
        currency: str | None = None,
        content_ids: list[str] | None = None,
        email: str | None = None,
        external_id: str | None = None,
        test_code: str | None = None,
    ) -> dict[str, Any]:
        """Send WhatsApp conversion event (async)"""
        payload = self._build_payload(
            account_id=account_id,
            event_name=event_name,
            event_time=event_time,
            event_id=event_id,
            conversation_id=conversation_id,
            phone_e164=phone_e164,
            value=value,
            currency=currency,
            content_ids=content_ids,
            email=email,
            external_id=external_id,
            test_code=test_code,
        )
        return await self._client._apost("/v1/whatsapp/conversions", data=payload)
