"""
Auto-generated workflows resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..client.base import BaseClient


class WorkflowsResource:
    """
    workflows operations.
    """

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    def _build_params(self, **kwargs: Any) -> dict[str, Any]:
        """Build query parameters, filtering None and empty-string values.

        Empty strings are filtered because MCP tool wrappers pass ``""`` as the
        default for optional string args, and the API rejects empty query
        values (e.g. ``platform=``) with a 400. Filtering here keeps both direct
        SDK callers and MCP tool callers safe.
        """

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        return {to_camel(k): v for k, v in kwargs.items() if v is not None and v != ""}

    def _build_payload(self, **kwargs: Any) -> dict[str, Any]:
        """Build request payload, filtering None values."""
        from datetime import datetime

        def to_camel(s: str) -> str:
            parts = s.split("_")
            return parts[0] + "".join(p.title() for p in parts[1:])

        result: dict[str, Any] = {}
        for k, v in kwargs.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                result[to_camel(k)] = v.isoformat()
            else:
                result[to_camel(k)] = v
        return result

    def list_workflows(
        self,
        *,
        profile_id: str | None = None,
        status: str | None = None,
        limit: int | None = 50,
        skip: int | None = 0,
    ) -> dict[str, Any]:
        """List workflows"""
        params = self._build_params(
            profile_id=profile_id,
            status=status,
            limit=limit,
            skip=skip,
        )
        return self._client._get("/v1/workflows", params=params)

    def create_workflow(
        self,
        profile_id: str,
        account_id: str,
        name: str,
        *,
        platform: str | None = "whatsapp",
        description: str | None = None,
        nodes: list[Any] | None = None,
        edges: list[Any] | None = None,
        entry_node_id: str | None = None,
    ) -> dict[str, Any]:
        """Create workflow"""
        payload = self._build_payload(
            profile_id=profile_id,
            account_id=account_id,
            platform=platform,
            name=name,
            description=description,
            nodes=nodes,
            edges=edges,
            entry_node_id=entry_node_id,
        )
        return self._client._post("/v1/workflows", data=payload)

    def get_workflow(self, workflow_id: str) -> dict[str, Any]:
        """Get workflow with graph"""
        return self._client._get(f"/v1/workflows/{workflow_id}")

    def update_workflow(
        self,
        workflow_id: str,
        *,
        name: str | None = None,
        description: str | None = None,
        nodes: list[Any] | None = None,
        edges: list[Any] | None = None,
        entry_node_id: Any | None = None,
        account_id: str | None = None,
    ) -> dict[str, Any]:
        """Update workflow"""
        payload = self._build_payload(
            name=name,
            description=description,
            nodes=nodes,
            edges=edges,
            entry_node_id=entry_node_id,
            account_id=account_id,
        )
        return self._client._patch(f"/v1/workflows/{workflow_id}", data=payload)

    def delete_workflow(self, workflow_id: str) -> dict[str, Any]:
        """Delete workflow"""
        return self._client._delete(f"/v1/workflows/{workflow_id}")

    def activate_workflow(self, workflow_id: str) -> dict[str, Any]:
        """Activate workflow"""
        return self._client._post(f"/v1/workflows/{workflow_id}/activate")

    def pause_workflow(self, workflow_id: str) -> dict[str, Any]:
        """Pause workflow"""
        return self._client._post(f"/v1/workflows/{workflow_id}/pause")

    def list_workflow_executions(
        self,
        workflow_id: str,
        *,
        status: str | None = None,
        limit: int | None = 25,
        skip: int | None = 0,
    ) -> dict[str, Any]:
        """List workflow runs"""
        params = self._build_params(
            status=status,
            limit=limit,
            skip=skip,
        )
        return self._client._get(
            f"/v1/workflows/{workflow_id}/executions", params=params
        )

    def trigger_workflow(
        self,
        workflow_id: str,
        *,
        to: str | None = None,
        conversation_id: str | None = None,
        text: str | None = None,
    ) -> dict[str, Any]:
        """Manually start a workflow run"""
        payload = self._build_payload(
            to=to,
            conversation_id=conversation_id,
            text=text,
        )
        return self._client._post(
            f"/v1/workflows/{workflow_id}/executions", data=payload
        )

    def list_workflow_execution_events(
        self, workflow_id: str, execution_id: str
    ) -> dict[str, Any]:
        """Get an execution's timeline"""
        return self._client._get(
            f"/v1/workflows/{workflow_id}/executions/{execution_id}/events"
        )

    def duplicate_workflow(self, workflow_id: str) -> dict[str, Any]:
        """Duplicate a workflow"""
        return self._client._post(f"/v1/workflows/{workflow_id}/duplicate")

    def list_workflow_versions(self, workflow_id: str) -> dict[str, Any]:
        """List a workflow's version history"""
        return self._client._get(f"/v1/workflows/{workflow_id}/versions")

    def get_workflow_version(self, workflow_id: str, version: int) -> dict[str, Any]:
        """Get a specific workflow version"""
        return self._client._get(f"/v1/workflows/{workflow_id}/versions/{version}")

    def restore_workflow_version(
        self, workflow_id: str, version: int
    ) -> dict[str, Any]:
        """Restore a workflow version"""
        return self._client._post(
            f"/v1/workflows/{workflow_id}/versions/{version}/restore"
        )

    async def alist_workflows(
        self,
        *,
        profile_id: str | None = None,
        status: str | None = None,
        limit: int | None = 50,
        skip: int | None = 0,
    ) -> dict[str, Any]:
        """List workflows (async)"""
        params = self._build_params(
            profile_id=profile_id,
            status=status,
            limit=limit,
            skip=skip,
        )
        return await self._client._aget("/v1/workflows", params=params)

    async def acreate_workflow(
        self,
        profile_id: str,
        account_id: str,
        name: str,
        *,
        platform: str | None = "whatsapp",
        description: str | None = None,
        nodes: list[Any] | None = None,
        edges: list[Any] | None = None,
        entry_node_id: str | None = None,
    ) -> dict[str, Any]:
        """Create workflow (async)"""
        payload = self._build_payload(
            profile_id=profile_id,
            account_id=account_id,
            platform=platform,
            name=name,
            description=description,
            nodes=nodes,
            edges=edges,
            entry_node_id=entry_node_id,
        )
        return await self._client._apost("/v1/workflows", data=payload)

    async def aget_workflow(self, workflow_id: str) -> dict[str, Any]:
        """Get workflow with graph (async)"""
        return await self._client._aget(f"/v1/workflows/{workflow_id}")

    async def aupdate_workflow(
        self,
        workflow_id: str,
        *,
        name: str | None = None,
        description: str | None = None,
        nodes: list[Any] | None = None,
        edges: list[Any] | None = None,
        entry_node_id: Any | None = None,
        account_id: str | None = None,
    ) -> dict[str, Any]:
        """Update workflow (async)"""
        payload = self._build_payload(
            name=name,
            description=description,
            nodes=nodes,
            edges=edges,
            entry_node_id=entry_node_id,
            account_id=account_id,
        )
        return await self._client._apatch(f"/v1/workflows/{workflow_id}", data=payload)

    async def adelete_workflow(self, workflow_id: str) -> dict[str, Any]:
        """Delete workflow (async)"""
        return await self._client._adelete(f"/v1/workflows/{workflow_id}")

    async def aactivate_workflow(self, workflow_id: str) -> dict[str, Any]:
        """Activate workflow (async)"""
        return await self._client._apost(f"/v1/workflows/{workflow_id}/activate")

    async def apause_workflow(self, workflow_id: str) -> dict[str, Any]:
        """Pause workflow (async)"""
        return await self._client._apost(f"/v1/workflows/{workflow_id}/pause")

    async def alist_workflow_executions(
        self,
        workflow_id: str,
        *,
        status: str | None = None,
        limit: int | None = 25,
        skip: int | None = 0,
    ) -> dict[str, Any]:
        """List workflow runs (async)"""
        params = self._build_params(
            status=status,
            limit=limit,
            skip=skip,
        )
        return await self._client._aget(
            f"/v1/workflows/{workflow_id}/executions", params=params
        )

    async def atrigger_workflow(
        self,
        workflow_id: str,
        *,
        to: str | None = None,
        conversation_id: str | None = None,
        text: str | None = None,
    ) -> dict[str, Any]:
        """Manually start a workflow run (async)"""
        payload = self._build_payload(
            to=to,
            conversation_id=conversation_id,
            text=text,
        )
        return await self._client._apost(
            f"/v1/workflows/{workflow_id}/executions", data=payload
        )

    async def alist_workflow_execution_events(
        self, workflow_id: str, execution_id: str
    ) -> dict[str, Any]:
        """Get an execution's timeline (async)"""
        return await self._client._aget(
            f"/v1/workflows/{workflow_id}/executions/{execution_id}/events"
        )

    async def aduplicate_workflow(self, workflow_id: str) -> dict[str, Any]:
        """Duplicate a workflow (async)"""
        return await self._client._apost(f"/v1/workflows/{workflow_id}/duplicate")

    async def alist_workflow_versions(self, workflow_id: str) -> dict[str, Any]:
        """List a workflow's version history (async)"""
        return await self._client._aget(f"/v1/workflows/{workflow_id}/versions")

    async def aget_workflow_version(
        self, workflow_id: str, version: int
    ) -> dict[str, Any]:
        """Get a specific workflow version (async)"""
        return await self._client._aget(
            f"/v1/workflows/{workflow_id}/versions/{version}"
        )

    async def arestore_workflow_version(
        self, workflow_id: str, version: int
    ) -> dict[str, Any]:
        """Restore a workflow version (async)"""
        return await self._client._apost(
            f"/v1/workflows/{workflow_id}/versions/{version}/restore"
        )
